[package]
name = "migrator"
version = "0.1.0"
edition = "2024"

[dependencies]
async-trait = "0.1.88"
sqlx_migrator = { version = "0.17.0", features = ["postgres"] }
tokio = { version = "1.40.0", features = ["full"] }
sqlx = { version = "0.8.2", features = [
  "runtime-tokio",
  "tls-native-tls",
  "postgres",
  "uuid",
  "json",
  "chrono",
] }
