project:
  type: website
  preview:
    port: 3950

website:
  title: "CatColab RFCs"
  # Navigation
  sidebar:
    style: "docked"
    collapse-level: 1
    contents:
      - index.md
      - auto: "*.md"
  # GitHub links
  repo-url: https://github.com/ToposInstitute/CatColab
  repo-subdir: rfc
  repo-actions: [source, issue]

format:
  html:
    # General styling
    theme:
      light: [flatly, custom.scss]
      dark: [darkly, custom.scss]
    respect-user-color-scheme: true
    # RFC rendering
    html-math-method: katex
    toc: true
    toc-depth: 5
    toc-expand: true
    number-sections: true
    date-format: YYYY-MM-DD
    csl: chicago-author-date.csl
  pdf:
    include-in-header:
      text: |
        \usepackage{mathtools}
        \usepackage{tikz-cd}
        \usepackage{quiver}
        \usepackage{ebproof}
        \ebproofnewstyle{small}{template=\footnotesize$\inserttext$}

filters:
  - filters.lua
