project:
  type: website

website:
  title: "CatColab RFCs"
  # Navigation
  sidebar:
    style: "docked"
    contents:
      - index.md
      - auto: "*.md"
  # GitHub links
  repo-url: https://github.com/ToposInstitute/CatColab
  repo-subdir: rfc
  repo-actions: [source, issue]

format:
  html:
    # General styling
    theme:
      light: [flatly, custom.scss]
      dark: [darkly, custom.scss]
    respect-user-color-scheme: true
    # RFC rendering
    html-math-method: katex
    toc: true
    toc-depth: 5
    toc-expand: true
    number-sections: true
    date-format: YYYY-MM-DD

filters:
  - filters.lua
