// GENERATED by theory-codegen — do not edit.
// Regenerate with: cargo run -p theory-codegen

import type { MorphismCell, ObjectCell } from "catcolab-documents";
import { basicMorphism, defineShape } from "catcolab-documents";

import { ThSchema } from "catlog-wasm";

const entityObType = { tag: "Basic", content: "Entity" } as const;
const attrTypeObType = { tag: "Basic", content: "AttrType" } as const;
const mappingMorType = { tag: "Hom", content: entityObType } as const;

export const SimpleSchema = defineShape({
    theory: "simple-schema",
    coreTheory: new ThSchema().theory(),
    objects: {
        Entity: entityObType,
        AttrType: attrTypeObType,
    },
    morphisms: {
        Mapping: mappingMorType,
        Attr: basicMorphism("Attr", entityObType, attrTypeObType),
    },
});

export const { Entity, AttrType } = SimpleSchema.objects;
export const { Mapping, Attr } = SimpleSchema.morphisms;

export type EntityCell = ObjectCell<typeof Entity>;
export type AttrTypeCell = ObjectCell<typeof AttrType>;
export type MappingCell = MorphismCell<typeof Mapping>;
export type AttrCell = MorphismCell<typeof Attr>;
