// GENERATED by theory-codegen — do not edit.
// Regenerate with: cargo run -p theory-codegen

import type { MorphismCell, ObjectCell } from "catcolab-documents";
import { defineShape } from "catcolab-documents";

import { ThCategory } from "catlog-wasm";

const typeObType = { tag: "Basic", content: "Object" } as const;
const aspectMorType = { tag: "Hom", content: typeObType } as const;

export const SimpleOlog = defineShape({
    theory: "simple-olog",
    coreTheory: new ThCategory().theory(),
    objects: {
        Type: typeObType,
    },
    morphisms: {
        Aspect: aspectMorType,
    },
    migrations: [
        {
            target: "simple-schema",
            migrate: ThCategory.toSchema,
        },
    ],
});

export const { Type } = SimpleOlog.objects;
export const { Aspect } = SimpleOlog.morphisms;

export type TypeCell = ObjectCell<typeof Type>;
export type AspectCell = MorphismCell<typeof Aspect>;
