# 9 days, in minutes
minimumReleaseAge: 12960
minimumReleaseAgeExclude:
  - wasm-pack
packages:
  - "dev-docs"
  - "packages/backend/pkg"
  - "packages/frontend"
  - "packages/document-methods"
  - "packages/ui-components"
  - "packages/gaios"

