# 9 days, in minutes
minimumReleaseAge: 12960
packages:
  - "dev-docs"
  - "packages/backend/pkg"
  - "packages/frontend"
  - "packages/notebook-types"
  - "packages/patchwork"
  - "packages/ui-components"
