packages:
    - "dev-docs"
    - "packages/automerge-doc-server"
    - "packages/backend/pkg"
    - "packages/frontend"
    - "packages/gaios"
    - "packages/notebook-types"
    - "packages/patchwork"
    - "packages/ui-components"
    - "packages/patchwork"
