//! Finitely presented categories.
//!
//! A *finitely presented category*, or *f.p. category* for short, is a [finite
//! graph](super::graph::FinGraph) together with a finite set of [path
//! equations](super::path::PathEq). This data defines a category whose objects are
//! the vertices of the graph and morphisms are paths in the graphs, regarded as
//! equivalent under the congruence relation generated by the path equations. For a
//! detailed description of this congruence relation, see ([Spivak
//! 2014](crate::refs::CTForTheSciences), Definition 4.5.2.3).
//!
//! In general, this congruence relation---the word problem for finitely presented
//! categories---cannot be decided, though in practice it often can be. The data
//! structure in this module uses [e-graphs](https://en.wikipedia.org/wiki/E-graph)
//! to check for equivalence of paths under the congruence.

use std::cell::RefCell;
use std::collections::HashMap;

use derivative::Derivative;
use egglog::ast::{Command, Expr, RunConfig, Schedule, Schema};
use egglog::prelude::*;
use nonempty::NonEmpty;
use thiserror::Error;

use super::{category::*, graph::*, path::*};
use crate::egglog_util::EGraphUtils;
use crate::validate::{self, Validate};
use crate::zero::{Column, HashColumn, MutMapping, QualifiedName};

/// A finitely presented category backed by an e-graph.
///
/// A data structure for a f.p. category in which the congruence relation generated
/// by the path equations is maintained by an e-graph. The question of whether paths
/// in the presented category are equivalent is referred to the e-graph.
///
/// # Interior mutability
///
/// Checking equivalence of paths requires mutating the underlying e-graph. However,
/// we do not want to regard this check as mutating, for the theoretical reason that
/// the check does not change the category presented and the practical reason that
/// it would cause mutable references to be aggressively propagated throughout the
/// codebase. Thus, we use the [interior
/// mutability](https://doc.rust-lang.org/book/ch15-05-interior-mutability.html)
/// pattern to encapsulate the mutability of the e-graph and perform borrow checking
/// at runtime. The current implementation allows only *single-threaded* usage.
#[derive(Clone, Derivative)]
#[derivative(Debug, Default(new = "true"), PartialEq, Eq)]
pub struct FpCategory {
    generators: HashGraph<QualifiedName, QualifiedName>,
    equations: HashColumn<QualifiedName, QualifiedPathEq>,
    #[derivative(Debug = "ignore", PartialEq = "ignore")]
    state: RefCell<CategoryEGraph>,
}

impl FpCategory {
    /// Gets the generating graph of the category presentation.
    pub fn generators(&self) -> &impl FinGraph<V = QualifiedName, E = QualifiedName> {
        &self.generators
    }

    /// Gets the path equations of the category presentation.
    pub fn equations(&self) -> impl Iterator<Item = &QualifiedPathEq> {
        self.equations.values()
    }

    /// Is the category freely generated?
    pub fn is_free(&self) -> bool {
        self.equations.is_empty()
    }

    /// Adds an object generator.
    pub fn add_ob_generator(&mut self, v: QualifiedName) {
        assert!(self.generators.add_vertex(v.clone()), "Object generator already exists");
        let state = self.state.get_mut();
        let expr = state.ob_generator(v);
        state.egraph.run_action(action!((unquote expr))).unwrap();
    }

    /// Adds several object generators at once.
    pub fn add_ob_generators(&mut self, iter: impl IntoIterator<Item = QualifiedName>) {
        for v in iter {
            self.add_ob_generator(v)
        }
    }

    /// Adds a morphism generator.
    pub fn add_mor_generator(&mut self, e: QualifiedName, dom: QualifiedName, cod: QualifiedName) {
        assert!(
            self.generators.add_edge(e.clone(), dom.clone(), cod.clone()),
            "Morphism generator already exists"
        );
        let state = self.state.get_mut();
        let (dom, cod) = (state.ob_generator(dom), state.ob_generator(cod));
        let mor = state.mor_generator(e);
        let actions = actions![
            (unquote mor.clone())
            (union (unquote dom) (dom (unquote mor.clone())))
            (union (unquote cod) (cod (unquote mor)))
        ];
        state.egraph.run_actions(actions).unwrap();
    }

    /// Adds a morphism generator without declaring its (co)domain.
    pub fn make_mor_generator(&mut self, e: QualifiedName) {
        assert!(self.generators.make_edge(e.clone()), "Morphism generator already exists");
        let state = self.state.get_mut();
        let expr = state.mor_generator(e);
        state.egraph.run_action(action!((unquote expr))).unwrap();
    }

    /// Gets the domain of a morphism generator.
    pub fn get_dom(&self, e: &QualifiedName) -> Option<&QualifiedName> {
        self.generators.get_src(e)
    }

    /// Gets the codomain of a morphism generator.
    pub fn get_cod(&self, e: &QualifiedName) -> Option<&QualifiedName> {
        self.generators.get_tgt(e)
    }

    /// Sets the domain of a morphism generator.
    pub fn set_dom(&mut self, e: QualifiedName, v: QualifiedName) {
        assert!(
            self.generators.set_src(e.clone(), v.clone()).is_none(),
            "Domain of morphism generator should not already be set"
        );
        let state = self.state.get_mut();
        let (mor, ob) = (state.mor_generator(e), state.ob_generator(v));
        let action = action!((union (unquote ob) (dom (unquote mor))));
        state.egraph.run_action(action).unwrap();
    }

    /// Sets the codomain of a morphism generator.
    pub fn set_cod(&mut self, e: QualifiedName, v: QualifiedName) {
        assert!(
            self.generators.set_tgt(e.clone(), v.clone()).is_none(),
            "Codomain of morphism generator should not already be set"
        );
        let state = self.state.get_mut();
        let (mor, ob) = (state.mor_generator(e), state.ob_generator(v));
        let action = action!((union (unquote ob) (cod (unquote mor))));
        state.egraph.run_action(action).unwrap();
    }

    /// Adds a path equation to the presentation.
    pub fn add_equation(&mut self, name: QualifiedName, eq: QualifiedPathEq) {
        assert!(
            self.equations.set(name, eq.clone()).is_none(),
            "Equation with given name already exists"
        );
        let (lhs, rhs) = (self.path_expr(eq.lhs), self.path_expr(eq.rhs));
        let action = action!((union (unquote lhs) (unquote rhs)));
        self.state.get_mut().egraph.run_action(action).unwrap();
    }

    /// Equates two path in the presentation.
    pub fn equate(&mut self, name: QualifiedName, lhs: QualifiedPath, rhs: QualifiedPath) {
        self.add_equation(name, PathEq::new(lhs, rhs));
    }

    fn path_expr(&self, path: QualifiedPath) -> Expr {
        path.map_reduce(
            |v| {
                let ob = self.state.borrow_mut().ob_generator(v);
                expr!((id (unquote ob)))
            },
            |e| self.state.borrow_mut().mor_generator(e),
            |f, g| expr!((compose (unquote f) (unquote g))),
        )
    }

    /// Iterates over failures to be a well-defined presentation of a category.
    pub fn iter_invalid(&self) -> impl Iterator<Item = InvalidFpCategory> + '_ {
        let generator_errors = self.generators.iter_invalid().map(|err| match err {
            InvalidGraph::Src(e) => InvalidFpCategory::Dom(e),
            InvalidGraph::Tgt(e) => InvalidFpCategory::Cod(e),
        });
        let equation_errors = self.equations.iter().filter_map(|(name, eq)| {
            Some(InvalidFpCategory::Eqn(name, eq.validate_in(&self.generators).err()?))
        });
        generator_errors.chain(equation_errors)
    }
}

impl Category for FpCategory {
    type Ob = QualifiedName;
    type Mor = QualifiedPath;

    fn has_ob(&self, x: &Self::Ob) -> bool {
        self.generators.has_vertex(x)
    }
    fn has_mor(&self, path: &Self::Mor) -> bool {
        path.contained_in(&self.generators)
    }
    fn dom(&self, path: &Self::Mor) -> Self::Ob {
        path.src(&self.generators)
    }
    fn cod(&self, path: &Self::Mor) -> Self::Ob {
        path.tgt(&self.generators)
    }

    fn compose(&self, path: Path<Self::Ob, Self::Mor>) -> Self::Mor {
        path.flatten_in(&self.generators).expect("Paths should be composable")
    }
    fn compose2(&self, path1: Self::Mor, path2: Self::Mor) -> Self::Mor {
        path1
            .concat_in(&self.generators, path2)
            .expect("Target of first path should equal source of second path")
    }

    fn morphisms_are_equal(&self, path1: Self::Mor, path2: Self::Mor) -> bool {
        let (lhs, rhs) = (self.path_expr(path1), self.path_expr(path2));
        self.state.borrow_mut().check_equal(lhs, rhs)
    }
}

impl FgCategory for FpCategory {
    type ObGen = QualifiedName;
    type MorGen = QualifiedName;

    fn ob_generators(&self) -> impl Iterator<Item = Self::ObGen> {
        self.generators.vertices()
    }
    fn mor_generators(&self) -> impl Iterator<Item = Self::MorGen> {
        self.generators.edges()
    }
    fn mor_generator_dom(&self, f: &Self::MorGen) -> Self::Ob {
        self.generators.src(f)
    }
    fn mor_generator_cod(&self, f: &Self::MorGen) -> Self::Ob {
        self.generators.tgt(f)
    }
}

impl Validate for FpCategory {
    type ValidationError = InvalidFpCategory;

    fn validate(&self) -> Result<(), NonEmpty<Self::ValidationError>> {
        validate::wrap_errors(self.iter_invalid())
    }
}

/// A failure of a finite presentation of a category to be well defined.
#[derive(Debug, Error)]
pub enum InvalidFpCategory {
    /// Morphism generator with an invalid domain.
    #[error("Domain of morphism generator `{0}` is not in the category")]
    Dom(QualifiedName),

    /// Morphism generator with an invalid codomain.
    #[error("Codomain of morphism generator `{0}` is not in the category")]
    Cod(QualifiedName),

    /// Path equation with one or more errors.
    #[error("Path equation `{0}` is not valid: `{1:?}`")]
    Eqn(QualifiedName, NonEmpty<InvalidPathEq>),
}

/// E-graph state for computing with categories in egglog.
///
/// Wraps an [`EGraph`] initialized with the theory of categories, along with
/// mappings from vertices and edges in the category's generating graph to numeric
/// IDs for generator terms in egglog.
#[derive(Clone)]
struct CategoryEGraph {
    egraph: EGraph,
    ob_generators: HashMap<QualifiedName, usize>,
    mor_generators: HashMap<QualifiedName, usize>,
}

impl CategoryEGraph {
    /// Constructs an object generator expression, assigning an ID if needed.
    fn ob_generator(&mut self, v: QualifiedName) -> Expr {
        let n = self.ob_generators.len();
        let id: i64 = (*self.ob_generators.entry(v).or_insert(n))
            .try_into()
            .expect("Shouldn't have too many object generators");
        expr!((ObGen (unquote exprs::int(id))))
    }

    /// Constructs a morphism generator expression, assigning an ID if needed.
    fn mor_generator(&mut self, e: QualifiedName) -> Expr {
        let n = self.mor_generators.len();
        let id: i64 = (*self.mor_generators.entry(e).or_insert(n))
            .try_into()
            .expect("Shouldn't have too many morphism generators");
        expr!((MorGen (unquote exprs::int(id))))
    }
}

impl CategoryEGraph {
    /// Checks whether two morphism expressions are equal.
    ///
    /// The category axioms are saturated before performing the check.
    fn check_equal(&mut self, lhs: Expr, rhs: Expr) -> bool {
        let schedule = Schedule::Saturate(
            span!(),
            Box::new(Schedule::Run(
                span!(),
                RunConfig { ruleset: "CatAxioms".into(), until: None },
            )),
        );
        let prog = vec![
            Command::Action(action!((unquote lhs.clone()))),
            Command::Action(action!((unquote rhs.clone()))),
            Command::RunSchedule(schedule),
        ];
        self.egraph.run_program(prog).unwrap();
        self.egraph.check_equal(lhs, rhs).unwrap()
    }
}

impl Default for CategoryEGraph {
    fn default() -> Self {
        let mut egraph = EGraph::default();
        init_category_egraph(&mut egraph).expect("Unexpected egglog error");
        Self {
            egraph,
            ob_generators: Default::default(),
            mor_generators: Default::default(),
        }
    }
}

/// Initializes an e-graph with the theory of categories.
fn init_category_egraph(egraph: &mut EGraph) -> Result<(), egglog::Error> {
    // Types: objects and morphisms with generators.
    datatype!(egraph, (datatype Ob (ObGen i64 :cost 0)));
    datatype!(egraph, (datatype Mor (MorGen i64 :cost 0) (compose Mor Mor :cost 1)));

    // Additional constructors: (co)domain and identity.
    for name in ["dom", "cod"] {
        add_constructor(
            egraph,
            name,
            Schema {
                input: vec!["Mor".into()],
                output: "Ob".into(),
            },
            Some(1),
            false,
        )?;
    }
    add_constructor(
        egraph,
        "id",
        Schema {
            input: vec!["Ob".into()],
            output: "Mor".into(),
        },
        Some(1),
        false,
    )?;

    // Predicate: is the morphism well-typed?
    add_relation(egraph, "is_mor_valid", vec!["Mor".into()])?;

    // Rule set: all the axioms for a category.
    add_ruleset(egraph, "CatAxioms")?;

    // Rule: every morphism generator is well-typed.
    rule(egraph, "CatAxioms", facts![(= f (MorGen name))], actions![(is_mor_valid f)])?;

    // Rule: every identity morphism is well-typed.
    rule(egraph, "CatAxioms", facts![(= f (id x))], actions![(is_mor_valid f)])?;

    // Rule: a composite of two morphisms is well-typed if both
    // morphisms are well-typed and their (co)domains are compatible.
    rule(
        egraph,
        "CatAxioms",
        facts![
            (= fg (compose f g))
            (is_mor_valid f)
            (is_mor_valid g)
            (= (cod f) (dom g))
        ],
        actions![(is_mor_valid fg)],
    )?;

    // Rules: (co)domains of composites and identities.
    rule(
        egraph,
        "CatAxioms",
        facts![
            (= fg (compose f g))
            (is_mor_valid fg)
        ],
        actions![
            (union (dom fg) (dom f))
            (union (cod fg) (cod g))
        ],
    )?;
    rule(egraph, "CatAxioms", facts![(= lhs (dom (id x)))], actions![(union lhs x)])?;
    rule(egraph, "CatAxioms", facts![(= lhs (cod (id x)))], actions![(union lhs x)])?;

    // Associativity axioms (bidirectional).
    rule(
        egraph,
        "CatAxioms",
        facts![
            (= fgh (compose (compose f g) h))
            (is_mor_valid fgh)
        ],
        actions![(union fgh (compose f (compose g h)))],
    )?;
    rule(
        egraph,
        "CatAxioms",
        facts![
            (= fgh (compose f (compose g h)))
            (is_mor_valid fgh)
        ],
        actions![(union fgh (compose (compose f g) h))],
    )?;

    // Unitality axioms.
    rule(
        egraph,
        "CatAxioms",
        facts![(= lhs (compose f (id (cod f))))],
        actions![(union lhs f)],
    )?;
    rule(
        egraph,
        "CatAxioms",
        facts![(= lhs (compose (id (dom f)) f))],
        actions![(union lhs f)],
    )?;

    Ok(())
}

#[cfg(test)]
use crate::zero::name;

/// The schema for graphs, an f.p. category.
#[cfg(test)]
pub fn sch_graph() -> FpCategory {
    let mut cat = FpCategory::new();
    cat.add_ob_generators([name("V"), name("E")]);
    cat.add_mor_generator(name("src"), name("E"), name("V"));
    cat.add_mor_generator(name("tgt"), name("E"), name("V"));
    cat
}

/// The schema for symmetric graphs, an f.p. category.
#[cfg(test)]
pub fn sch_sgraph() -> FpCategory {
    let mut cat = FpCategory::new();
    cat.add_ob_generators([name("V"), name("E")]);
    cat.add_mor_generator(name("src"), name("E"), name("V"));
    cat.add_mor_generator(name("tgt"), name("E"), name("V"));
    cat.add_mor_generator(name("inv"), name("E"), name("E"));
    cat.equate(
        name("involutivity"),
        Path::pair(name("inv"), name("inv")),
        Path::empty(name("E")),
    );
    cat.equate(name("inv_src"), Path::pair(name("inv"), name("src")), Path::single(name("tgt")));
    cat.equate(name("inv_tgt"), Path::pair(name("inv"), name("tgt")), Path::single(name("src")));
    cat
}

/// The schema for half-edge graphs, an f.p. category.
#[cfg(test)]
pub fn sch_hgraph() -> FpCategory {
    let mut cat = FpCategory::new();
    cat.add_ob_generators([name("V"), name("H")]);
    cat.add_mor_generator(name("vert"), name("H"), name("V"));
    cat.add_mor_generator(name("inv"), name("H"), name("H"));
    cat.equate(
        name("involutivity"),
        Path::pair(name("inv"), name("inv")),
        Path::empty(name("H")),
    );
    cat
}

#[cfg(test)]
mod tests {
    use super::*;
    use nonempty::nonempty;

    #[test]
    fn sch_sgraph_equations() {
        let sch = sch_sgraph();
        assert!(!sch.is_free());
        assert!(sch.validate().is_ok());

        assert!(!sch.morphisms_are_equal(Path::single(name("src")), Path::single(name("tgt"))));
        assert!(
            sch.morphisms_are_equal(Path::pair(name("inv"), name("inv")), Path::empty(name("E")))
        );
        assert!(sch.morphisms_are_equal(
            Path::Seq(nonempty![name("inv"), name("inv"), name("inv"), name("src")]),
            Path::single(name("tgt"))
        ));
    }
}
