export { type ModelDocument, newModelDocument } from "../model";
export { type AnalysisDocument, newAnalysisDocument } from "./analysis";
export { type DiagramDocument, newDiagramDocument } from "./diagram";

export { plainStore, type DocumentStore, resolveModelInStore } from "./store";
export { binder, createBinder, type Binder, type Notebook } from "./notebook";
export { type Issue, type Result } from "./validation";
export {
    CellKind,
    RichText,
    Instantiation,
    defineObject,
    defineMorphism,
    defineAnalysis,
    defineIndividual,
    defineAspect,
    defineShape,
    type RichTextType,
    type InstantiationType,
    type ObjectDef,
    type ObjectCell,
    type EndpointOf,
    type Endpoints,
    type ModalityBrand,
    type MorEndpointMeta,
    type MorphismDef,
    type DomOf,
    type CodOf,
    type MorphismCell,
    type RichTextCell,
    type InstantiationSpecialization,
    type ValidatableNotebook,
    type InstantiationArgs,
    type InstantiationCell,
    type NotebookCell,
    type ModelMigration,
    type Shape,
    type ModelValidationResult,
    type AnalysisDef,
    type AnalysisCell,
    type AnalysisShape,
    type IndividualDef,
    type AspectDef,
    type IndividualCell,
    type AspectCell,
    type DiagramCell,
    type DiagramShape,
    type DiagramShapeOf,
    type DiagramValidationResult,
} from "./definitions";
