//! The default unification algorithm for composites of vertical arrows. See
//! [default_unify_vertical_arrows] for details.

use itertools::Itertools;

use crate::mtt::{
    composite::Composite,
    theory::{
        Theory, TheoryObject, TheoryVerticalArrow, UnificationResult,
        list_modality::OrderPreservingMap, modal_depth::ModalDepth,
    },
};

/// Default unification algorithm for composites of vertical arrows. The equations
/// recognised by this algorithm are generated by the naturality and coherence of
/// [TheoryVerticalArrow::ModalStructureMap].
pub fn default_unify_vertical_arrows<T: Theory>(
    composites: &[&Composite<TheoryVerticalArrow<T>>],
) -> UnificationResult<Composite<TheoryVerticalArrow<T>>> {
    // rule out empty case
    if composites.is_empty() {
        return UnificationResult::Incompatible;
    }

    // drag all ModalStructureMap to the front, destruct into Vec
    let normalised: Vec<_> = composites.iter().copied().map(destruct_normalise_composite).collect();

    // from here on, we are performing structural comparisons as we have a
    // chosen normal form.

    // rule out mismatches
    if !normalised.iter().map(Vec::len).all_equal() {
        return UnificationResult::Incompatible;
    }

    // unify atomically on the "transpose" per index
    let Some(pro_arrows) = (0..normalised[0].len())
        .map(|i| {
            let col: Vec<_> = normalised.iter().map(|row| &row[i]).collect();
            unify_arrow(&col).most_specific()
        })
        .collect::<Option<Vec<_>>>()
    else {
        return UnificationResult::Incompatible;
    };

    let Ok(result) = Composite::try_from(pro_arrows) else {
        // really this should be impossible if everything is law abiding
        return UnificationResult::Incompatible;
    };

    UnificationResult::MostSpecific(result)
}

/// Purely structural unification of parallel (base) theory arrows.
fn unify_arrow<T: Theory>(
    arrows: &[&TheoryVerticalArrow<T>],
) -> UnificationResult<TheoryVerticalArrow<T>> {
    let Some((first, rest)) = arrows.split_first() else {
        return UnificationResult::Incompatible;
    };
    match first {
        TheoryVerticalArrow::Generator { name, dom, cod } => {
            let mut doms: Vec<&TheoryObject<T>> = vec![dom];
            let mut cods: Vec<&TheoryObject<T>> = vec![cod];
            for a in rest {
                let TheoryVerticalArrow::Generator { name: n, dom: d, cod: c } = a else {
                    return UnificationResult::Incompatible;
                };
                if n != name {
                    return UnificationResult::Incompatible;
                }
                doms.push(d);
                cods.push(c);
            }
            let UnificationResult::MostSpecific(dom) = T::unify_objects(&doms) else {
                return UnificationResult::Incompatible;
            };
            let UnificationResult::MostSpecific(cod) = T::unify_objects(&cods) else {
                return UnificationResult::Incompatible;
            };
            UnificationResult::MostSpecific(TheoryVerticalArrow::Generator {
                name: name.clone(),
                dom,
                cod,
            })
        }

        TheoryVerticalArrow::ModalApplication(on) => {
            let mut children: Vec<&TheoryVerticalArrow<T>> = vec![on.as_ref()];
            for a in rest {
                let TheoryVerticalArrow::ModalApplication(on) = a else {
                    return UnificationResult::Incompatible;
                };
                children.push(on.as_ref());
            }
            unify_arrow(&children)
                .map(|child| TheoryVerticalArrow::ModalApplication(Box::new(child)))
        }
        TheoryVerticalArrow::ModalStructureMap(map) => {
            if rest
                .iter()
                .all(|a| matches!(a, TheoryVerticalArrow::ModalStructureMap(other) if other == map))
            {
                UnificationResult::MostSpecific(TheoryVerticalArrow::ModalStructureMap(map.clone()))
            } else {
                UnificationResult::Incompatible
            }
        }
    }
}

/// Take a [Composite] of [TheoryVerticalArrow]s to a normal form through a (hopefully)
/// confluent rewriting system. There is a preceding normalisation step to
/// ensure that [TheoryVerticalArrow::ModalApplication] of
/// [TheoryVerticalArrow::ModalStructureMap] becomes a top-level
/// [TheoryVerticalArrow::ModalStructureMap], followed by continual application of three
/// rewrites specified below, whenever they apply. The normalisation terminates
/// when no further rewrites are possible.
///
/// The first rewrite removes identity [TheoryVerticalArrow::ModalStructureMap]s.
/// The second takes two adjacent [TheoryVerticalArrow::ModalStructureMap]s and
/// composes them, while the third commutes [TheoryVerticalArrow::ModalStructureMap]
/// past (modal applications on) [TheoryVerticalArrow::Generator]s by naturality.
/// These are the only equations possible in the free theory on a modality and
/// generators.
fn destruct_normalise_composite<T: Theory>(
    composite: &Composite<TheoryVerticalArrow<T>>,
) -> Vec<TheoryVerticalArrow<T>> {
    // Rewrite 1: per-arrow, absorb any prefix of ModalApplication wrappers
    // sitting above a ModalStructureMap into the map via outer_lift.
    let mut arrows: Vec<_> =
        composite.iter().cloned().map(absorb_outer_modal_applications).collect();

    // A "bubble-sort" style loop to apply the three remaining rewrites for
    // the normal form.
    let mut done = false;
    while !done {
        done = true;
        for i in 0..arrows.len() {
            // Rewrite 2: remove identity ModalStructureMaps.
            if let TheoryVerticalArrow::ModalStructureMap(m) = &arrows[i]
                && m.is_identity()
            {
                arrows.remove(i);
                done = false;
                break;
            }

            // Rewrite 3: compose adjacent ModalStructureMaps.
            // Clippy collapses these `if`s into a chain, trading readability for unyielding uniformity.
            if let Some(TheoryVerticalArrow::ModalStructureMap(m2)) = arrows.get(i + 1)
                && let TheoryVerticalArrow::ModalStructureMap(m1) = &arrows[i]
                && let Some(composite) = OrderPreservingMap::compose(m1, m2)
            {
                arrows[i] = TheoryVerticalArrow::ModalStructureMap(composite);
                arrows.remove(i + 1);
                done = false;
                break;
            }

            // Rewrite 4: commute a ModalStructureMap leftward past a generator.
            // And again.
            if let Some(TheoryVerticalArrow::ModalStructureMap(map)) = arrows.get(i + 1)
                && is_eventually_generator(&arrows[i])
                && let Some((d_dom, d_cod)) = inner_generator_boundary_depths(&arrows[i])
                && let Some(map) = if d_dom >= d_cod {
                    Some(map.inner_lift(d_dom - d_cod))
                } else {
                    map.inner_unlift(d_cod - d_dom)
                }
            {
                let generator = arrows.remove(i);
                arrows[i] = TheoryVerticalArrow::ModalStructureMap(map);
                arrows.insert(i + 1, generator);
                done = false;
                break;
            }
        }
    }

    arrows
}

/// Determine whether a [TheoryVerticalArrow] is a generator, allowing for layers of
/// [TheoryVerticalArrow::ModalApplication].
fn is_eventually_generator<T: Theory>(arrow: &TheoryVerticalArrow<T>) -> bool {
    // Rust makes no guarantees about tail recursion, and in context by abusing the
    // normal form and the current state of the TheoryArrow enum it would be
    // possible to make a "shorter" implementation. In the face of these options, we
    // nevertheless choose obviousness over terseness, and force any changes to the
    // structure of the enum to also visit this decision point.
    match arrow {
        TheoryVerticalArrow::ModalStructureMap(_) => false,
        TheoryVerticalArrow::Generator { .. } => true,
        TheoryVerticalArrow::ModalApplication(on) => is_eventually_generator(on),
    }
}

/// Transform iterates of [TheoryVerticalArrow::ModalApplication] on
/// [TheoryVerticalArrow::ModalStructureMap] to a single
/// [TheoryVerticalArrow::ModalStructureMap] by using the [ListModality] structure.
fn absorb_outer_modal_applications<T: Theory>(
    arrow: TheoryVerticalArrow<T>,
) -> TheoryVerticalArrow<T> {
    let mut depth = 0;
    let mut cursor = &arrow;
    while let TheoryVerticalArrow::ModalApplication(on) = cursor {
        depth += 1;
        cursor = on.as_ref();
    }
    match cursor {
        TheoryVerticalArrow::ModalStructureMap(map) => {
            TheoryVerticalArrow::ModalStructureMap(map.outer_lift(depth))
        }
        TheoryVerticalArrow::Generator { .. } | TheoryVerticalArrow::ModalApplication(_) => arrow,
    }
}

/// Compute the modal depth of the domain and codomain (respectively) of a
/// [TheoryVerticalArrow::Generator], potentially wrapped in iterated layers of
/// [TheoryVerticalArrow::ModalApplication]. These additional layers do not contribute
/// to the computed depth. In any other case, return None.
fn inner_generator_boundary_depths<T: Theory>(
    arrow: &TheoryVerticalArrow<T>,
) -> Option<(usize, usize)> {
    let mut cursor = arrow;
    while let TheoryVerticalArrow::ModalApplication(on) = cursor {
        cursor = on.as_ref();
    }
    match cursor {
        TheoryVerticalArrow::Generator { dom, cod, .. } => {
            Some((dom.modal_depth(), cod.modal_depth()))
        }
        TheoryVerticalArrow::ModalStructureMap(_) | TheoryVerticalArrow::ModalApplication(_) => {
            None
        }
    }
}
