//! TODO: doc string

use itertools::Itertools;

use crate::mtt::{
    composite::Composite,
    theory::{
        Theory, TheoryArrow, TheoryObject, UnificationResult, list_modality::StructureMap,
        modal_depth::ModalDepth,
    },
};

/// Default unification algorithm for composites of vertical arrows. The equations
/// recognised by this algorithm are generated by the naturality and coherence of
/// [TheoryArrow::ModalStructureMap].
pub fn default_unify_vertical_arrows<T: Theory>(
    composites: &[&Composite<TheoryArrow<T>>],
) -> UnificationResult<Composite<TheoryArrow<T>>> {
    // rule out empty case
    if composites.is_empty() {
        return UnificationResult::Incompatible;
    }

    // drag all ModalStructureMap to the front, destruct into Vec
    let normalised: Vec<_> = composites.iter().copied().map(destruct_normalise_composite).collect();

    // from here on, we are performing structural comparisons as we have a
    // chosen normal form.

    // rule out mismatches
    if !normalised.iter().map(Vec::len).all_equal() {
        return UnificationResult::Incompatible;
    }

    // unify atomically on the "transpose" per index
    let Some(pro_arrows) = (0..normalised[0].len())
        .map(|i| {
            let col: Vec<_> = normalised.iter().map(|row| &row[i]).collect();
            unify_arrow(&col).most_specific()
        })
        .collect::<Option<Vec<_>>>()
    else {
        return UnificationResult::Incompatible;
    };

    let Ok(result) = Composite::try_from(pro_arrows) else {
        // really this should be impossible if everything is law abiding
        return UnificationResult::Incompatible;
    };

    UnificationResult::MostSpecific(result)
}

/// Purely structural unification of parallel (base) theory arrows.
fn unify_arrow<T: Theory>(arrows: &[&TheoryArrow<T>]) -> UnificationResult<TheoryArrow<T>> {
    let Some((first, rest)) = arrows.split_first() else {
        return UnificationResult::Incompatible;
    };
    match first {
        TheoryArrow::Generator { name, dom, cod } => {
            let mut doms: Vec<&TheoryObject<T>> = vec![dom];
            let mut cods: Vec<&TheoryObject<T>> = vec![cod];
            for a in rest {
                let TheoryArrow::Generator { name: n, dom: d, cod: c } = a else {
                    return UnificationResult::Incompatible;
                };
                if n != name {
                    return UnificationResult::Incompatible;
                }
                doms.push(d);
                cods.push(c);
            }
            let UnificationResult::MostSpecific(dom) = T::unify_objects(&doms) else {
                return UnificationResult::Incompatible;
            };
            let UnificationResult::MostSpecific(cod) = T::unify_objects(&cods) else {
                return UnificationResult::Incompatible;
            };
            UnificationResult::MostSpecific(TheoryArrow::Generator { name: name.clone(), dom, cod })
        }

        TheoryArrow::ModalApplication(on) => {
            let mut children: Vec<&TheoryArrow<T>> = vec![on.as_ref()];
            for a in rest {
                let TheoryArrow::ModalApplication(on) = a else {
                    return UnificationResult::Incompatible;
                };
                children.push(on.as_ref());
            }
            unify_arrow(&children).map(|child| TheoryArrow::ModalApplication(Box::new(child)))
        }
        TheoryArrow::ModalStructureMap(map) => {
            if rest
                .iter()
                .all(|a| matches!(a, TheoryArrow::ModalStructureMap(other) if other == map))
            {
                UnificationResult::MostSpecific(TheoryArrow::ModalStructureMap(map.clone()))
            } else {
                UnificationResult::Incompatible
            }
        }
    }
}

/// TODO: doc --- put a [Composite] of [TheoryArrow]s into the epi-mono normal
/// form for the theory's [ListModality] structure maps, using
/// [StructureMap::compose], [StructureMap::outer_lift], [StructureMap::inner_lift],
/// and [StructureMap::inner_unlift].

/// Take a [Composite] of [TheoryArrow]s to a normal form
fn destruct_normalise_composite<T: Theory>(
    composite: &Composite<TheoryArrow<T>>,
) -> Vec<TheoryArrow<T>> {
    // Rewrite 1: per-arrow, absorb any prefix of ModalApplication wrappers
    // sitting above a ModalStructureMap into the map via outer_lift.
    let mut arrows: Vec<_> =
        composite.iter().cloned().map(absorb_outer_modal_applications).collect();

    // A "bubble-sort" style loop to apply the two remaining rewrites for the
    // normal form.
    let mut done = false;
    while !done {
        done = true;
        for i in 0..arrows.len().saturating_sub(1) {
            // Rewrite 2: compose adjacent ModalStructureMaps
            if let TheoryArrow::ModalStructureMap(m1) = &arrows[i]
                && let TheoryArrow::ModalStructureMap(m2) = &arrows[i + 1]
                && let Some(composite) = StructureMap::compose(m1, m2)
            {
                arrows[i] = TheoryArrow::ModalStructureMap(composite);
                arrows.remove(i + 1);
                done = false;
                break;
            }

            // Rewrite 3: commute a ModalStructureMap leftward past a generator
            if let TheoryArrow::ModalStructureMap(map) = &arrows[i + 1]
                && is_eventually_generator(&arrows[i])
                && let Some((d_dom, d_cod)) = inner_generator_boundary_depths(&arrows[i])
                && let Some(map) = if d_dom >= d_cod {
                    Some(map.inner_lift(d_dom - d_cod))
                } else {
                    map.inner_unlift(d_cod - d_dom)
                }
            {
                let generator = arrows.remove(i);
                arrows[i] = TheoryArrow::ModalStructureMap(map);
                arrows.insert(i + 1, generator);
                done = false;
                break;
            }
        }
    }

    arrows
}

/// Determine whether a [TheoryArrow] is a generator, allowing for layers of
/// [TheoryArrow::ModalApplication].
fn is_eventually_generator<T: Theory>(arrow: &TheoryArrow<T>) -> bool {
    // Rust makes no guarantees about tail recursion, and in context by abusing the
    // normal form and the current state of the TheoryArrow enum it would be
    // possible to make a "shorter" implementation. In the face of these options, we
    // nevertheless choose obviousness over terseness, and force any changes to the
    // structure of the enum to also visit this decision point.
    match arrow {
        TheoryArrow::ModalStructureMap(_) => false,
        TheoryArrow::Generator { .. } => true,
        TheoryArrow::ModalApplication(on) => is_eventually_generator(on),
    }
}

/// Transform iterates of [TheoryArrow::ModalApplication] on
/// [TheoryArrow::ModalStructureMap] to a single
/// [TheoryArrow::ModalStructureMap] by using the [ListModality] structure.
fn absorb_outer_modal_applications<T: Theory>(arrow: TheoryArrow<T>) -> TheoryArrow<T> {
    let mut depth = 0;
    let mut cursor = &arrow;
    while let TheoryArrow::ModalApplication(on) = cursor {
        depth += 1;
        cursor = on.as_ref();
    }
    match cursor {
        TheoryArrow::ModalStructureMap(map) => {
            TheoryArrow::ModalStructureMap(map.outer_lift(depth))
        }
        TheoryArrow::Generator { .. } | TheoryArrow::ModalApplication(_) => arrow,
    }
}

/// Compute the modal depth of the domain and codomain (respectively) of a
/// [TheoryArrow::Generator], potentially wrapped in iterated layers of
/// [TheoryArrow::ModalApplication]. These additional layers do not contribute
/// to the computed depth. In any other case, return None.
fn inner_generator_boundary_depths<T: Theory>(arrow: &TheoryArrow<T>) -> Option<(usize, usize)> {
    let mut cursor = arrow;
    while let TheoryArrow::ModalApplication(on) = cursor {
        cursor = on.as_ref();
    }
    match cursor {
        TheoryArrow::Generator { dom, cod, .. } => Some((dom.modal_depth(), cod.modal_depth())),
        TheoryArrow::ModalStructureMap(_) | TheoryArrow::ModalApplication(_) => None,
    }
}
