//! TODO: doc string

use itertools::Itertools;

use crate::mtt::{
    binary_signature::BinarySignature,
    composite::Composite,
    hole::Holy,
    theory::{Theory, TheoryArrow, TheoryObject, TheoryProArrow, UnificationResult},
};

/// Default unification algorithm for composites of pro-arrows. The equations
/// recognised by this algorithm are generated by the unitality of
/// [TheoryProArrow::Hom] and the compatibility of hom with modalities:
/// `M(Hom(X)) = Hom(M(X))`.
pub fn default_unify_pro_arrows<T: Theory>(
    composites: &[&Composite<TheoryProArrow<T>>],
) -> UnificationResult<Composite<TheoryProArrow<T>>> {
    // With no composites there are no rigid demands, so the meet is the
    // most general pro-arrow: a singleton hole whose boundary is itself
    // unconstrained. This mirrors [default_unify_objects]'s handling
    // of an empty object collection, and lets the empty-list degenerate case
    // flow through the general element-unification path in synthesise_list.
    if composites.is_empty() {
        return UnificationResult::MostSpecific(Composite::singleton(
            TheoryProArrow::unconstrained("unify".to_string()),
        ));
    }

    let canonical_composites: Vec<Vec<_>> = composites
        .iter()
        .map(|c| c.iter().map(default_canonicalise_pro_arrow).collect())
        .collect();

    // Filter out homs after canonicalisation, because modal homs are unital too.
    let normalised: Vec<_> = canonical_composites
        .iter()
        .map(|c| c.iter().filter(|p| !matches!(p, TheoryProArrow::Hom(_))).collect::<Vec<_>>())
        .collect();

    // must all be the same length
    if !normalised.iter().map(Vec::len).all_equal() {
        return UnificationResult::Incompatible;
    }

    // if they're all empty now, we have a single hom if we can unify dom and cod
    if normalised[0].is_empty() {
        // It's a hom if the boundary is a single object, note that in general
        // this is stricter than first unifying domains & codomains separately,
        // before unifying the result.
        let boundary: Vec<_> = composites.iter().flat_map(|c| [c.dom(), c.cod()]).collect();
        let boundary_refs = &boundary.iter().collect::<Vec<_>>();
        return T::unify_objects(boundary_refs)
            .map(TheoryProArrow::Hom)
            .map(Composite::singleton);
    }

    // After canonicalisation and hom removal, there are no further equations
    // between composite positions.
    let Some(pro_arrows) = (0..normalised[0].len())
        .map(|i| {
            let col: Vec<_> = normalised.iter().map(|row| row[i]).collect();
            unify_pro_arrow(&col).most_specific()
        })
        .collect::<Option<Vec<_>>>()
    else {
        return UnificationResult::Incompatible;
    };

    let Ok(result) = Composite::try_from(pro_arrows) else {
        // really this should be impossible if everything is law abiding
        return UnificationResult::Incompatible;
    };

    UnificationResult::MostSpecific(result)
}

/// Unify a collection of canonical atomic pro-arrows.
fn unify_pro_arrow<T: Theory>(
    pro_arrows: &[&TheoryProArrow<T>],
) -> UnificationResult<TheoryProArrow<T>> {
    let doms = pro_arrows.iter().copied().map(TheoryProArrow::dom).collect::<Vec<_>>();
    let dom_refs = doms.iter().collect::<Vec<_>>();
    let UnificationResult::MostSpecific(dom) = T::unify_objects(&dom_refs) else {
        return UnificationResult::Incompatible;
    };

    let cods = pro_arrows.iter().copied().map(TheoryProArrow::cod).collect::<Vec<_>>();
    let cod_refs = cods.iter().collect::<Vec<_>>();
    let UnificationResult::MostSpecific(cod) = T::unify_objects(&cod_refs) else {
        return UnificationResult::Incompatible;
    };

    structural_pro_arrow_unification(pro_arrows, dom, cod)
}

/// Put a pro-arrow in the default normal form, pushing modalities on homs onto
/// their object: `M(Hom(X))` becomes `Hom(M(X))`.
fn default_canonicalise_pro_arrow<T: Theory>(pro_arrow: &TheoryProArrow<T>) -> TheoryProArrow<T> {
    match pro_arrow {
        TheoryProArrow::Hom(_) | TheoryProArrow::Generator { .. } | TheoryProArrow::Hole { .. } => {
            pro_arrow.clone()
        }
        TheoryProArrow::Restriction { base, dom_leg, cod_leg } => TheoryProArrow::Restriction {
            base: Box::new(default_canonicalise_pro_arrow(base)),
            dom_leg: dom_leg.clone(),
            cod_leg: cod_leg.clone(),
        },
        TheoryProArrow::ModalApplication(on) => {
            let on = default_canonicalise_pro_arrow(on);
            match on {
                TheoryProArrow::Hom(o) => {
                    TheoryProArrow::Hom(TheoryObject::ModalApplication(Box::new(o)))
                }
                TheoryProArrow::Generator { .. }
                | TheoryProArrow::Hole { .. }
                | TheoryProArrow::Restriction { .. }
                | TheoryProArrow::ModalApplication(_) => {
                    TheoryProArrow::ModalApplication(Box::new(on))
                }
            }
        }
    }
}

fn unwrap_modal_theory_object<T: Theory>(
    obj: TheoryObject<T>,
) -> Option<TheoryObject<T>> {
    match obj {
        TheoryObject::ModalApplication(on) => Some(*on),
        _ => None,
    }
}

/// Structural unification of a collection of atomic pro-arrows, after default
/// canonicalisation of modal homs.
///
/// `dom` and `cod` are the already-unified boundary objects the result must
/// span (see [default_unify_pro_arrows]); they are needed because a pro-arrow's
/// most general inhabitants --- a hole, and the parametric hom --- carry no
/// structure of their own beyond that boundary.
///
/// pro-arrows must all share a head, and we recurse on the remainder.
fn structural_pro_arrow_unification<T: Theory>(
    pro_arrows: &[&TheoryProArrow<T>],
    dom: TheoryObject<T>,
    cod: TheoryObject<T>,
) -> UnificationResult<TheoryProArrow<T>> {
    // we have dom & cod already, so don't need these
    let rigid: Vec<&TheoryProArrow<T>> =
        pro_arrows.iter().copied().filter(|p| !p.is_hole()).collect();

    // a hole is the most general solution in the case where we have no further
    // constraints
    let Some((first, rest)) = rigid.split_first() else {
        return UnificationResult::MostSpecific(TheoryProArrow::Hole {
            dom: dom.clone(),
            cod: cod.clone(),
        });
    };

    match first {
        TheoryProArrow::Hom(_) => {
            if rest.iter().any(|p| !matches!(p, TheoryProArrow::Hom(_))) {
                return UnificationResult::Incompatible;
            }
            T::unify_objects(&[&dom, &cod]).map(TheoryProArrow::Hom)
        }

        TheoryProArrow::Generator { name, .. } => {
            for p in rest {
                let TheoryProArrow::Generator { name: n, .. } = p else {
                    return UnificationResult::Incompatible;
                };
                if n != name {
                    return UnificationResult::Incompatible;
                }
            }
            UnificationResult::MostSpecific(TheoryProArrow::Generator {
                name: name.clone(),
                dom,
                cod,
            })
        }

        TheoryProArrow::Restriction { base, dom_leg, cod_leg } => {
            // The approach taken here is that we generate no equations between
            // P(f,g) and Q(h,k) unless P=Q, f=g, and h=k.
            let mut bases: Vec<&TheoryProArrow<T>> = vec![base.as_ref()];
            let mut dom_legs: Vec<&Composite<TheoryArrow<T>>> = vec![dom_leg];
            let mut cod_legs: Vec<&Composite<TheoryArrow<T>>> = vec![cod_leg];
            for o in rest {
                let TheoryProArrow::Restriction { base: b, dom_leg: dl, cod_leg: cl } = o else {
                    return UnificationResult::Incompatible;
                };
                bases.push(b.as_ref());
                dom_legs.push(dl);
                cod_legs.push(cl);
            }
            let UnificationResult::MostSpecific(base) = unify_pro_arrow(&bases) else {
                return UnificationResult::Incompatible;
            };
            let UnificationResult::MostSpecific(dom_leg) = T::unify_vertical_arrows(&dom_legs)
            else {
                return UnificationResult::Incompatible;
            };
            let UnificationResult::MostSpecific(cod_leg) = T::unify_vertical_arrows(&cod_legs)
            else {
                return UnificationResult::Incompatible;
            };
            UnificationResult::MostSpecific(TheoryProArrow::Restriction {
                base: Box::new(base),
                dom_leg,
                cod_leg,
            })
        }

        TheoryProArrow::ModalApplication(on) => {
            // The boundaries should be of the form "modality(dom)" and
            // "modality(cod)", so we "unwrap" the modality to obtain the dom
            // and cod objects so that we may recursively unify the "unwrapped"
            // pro-arrows.
            let Some(dom) = unwrap_modal_theory_object::<T>(dom) else {
                return UnificationResult::Incompatible;
            };
            let Some(cod) = unwrap_modal_theory_object::<T>(cod) else {
                return UnificationResult::Incompatible;
            };

            let mut unwrapped: Vec<&TheoryProArrow<T>> = vec![on.as_ref()];
            for p in rest {
                let TheoryProArrow::ModalApplication(on) = p else {
                    return UnificationResult::Incompatible;
                };
                unwrapped.push(on.as_ref());
            }

            structural_pro_arrow_unification(&unwrapped, dom, cod)
                .map(|result| TheoryProArrow::ModalApplication(Box::new(result)))
        }

        TheoryProArrow::Hole { .. } => unreachable!("holes were already filtered"),
    }
}
