//! TODO: doc string

use itertools::Itertools;

use crate::mtt::{
    composite::Composite,
    theory::{Theory, TheoryArrow, TheoryObject, UnificationResult},
};

/// Default unification algorithm for composites of vertical arrows. The equations
/// recognised by this algorithm are generated by the naturality and coherence of
/// [TheoryArrow::ModalStructureMap].
pub fn default_unify_vertical_arrows<T: Theory>(
    composites: &[&Composite<TheoryArrow<T>>],
) -> UnificationResult<Composite<TheoryArrow<T>>> {
    // rule out empty case
    if composites.is_empty() {
        return UnificationResult::Incompatible;
    }

    // drag all ModalStructureMap to the front, destruct into Vec
    let normalised: Vec<_> = composites.iter().copied().map(destruct_normalise_composite).collect();

    // from here on, we are performing structural comparisons as we have a
    // chosen normal form.

    // rule out mismatches
    if !normalised.iter().map(Vec::len).all_equal() {
        return UnificationResult::Incompatible;
    }

    // unify atomically on the "transpose" per index
    let Some(pro_arrows) = (0..normalised[0].len())
        .map(|i| {
            let col: Vec<_> = normalised.iter().map(|row| &row[i]).collect();
            unify_arrow(&col).most_specific()
        })
        .collect::<Option<Vec<_>>>()
    else {
        return UnificationResult::Incompatible;
    };

    let Ok(result) = Composite::try_from(pro_arrows) else {
        // really this should be impossible if everything is law abiding
        return UnificationResult::Incompatible;
    };

    UnificationResult::MostSpecific(result)
}

/// Purely structural unification of parallel (base) theory arrows.
fn unify_arrow<T: Theory>(arrows: &[&TheoryArrow<T>]) -> UnificationResult<TheoryArrow<T>> {
    let Some((first, rest)) = arrows.split_first() else {
        return UnificationResult::Incompatible;
    };
    match first {
        TheoryArrow::Generator { name, dom, cod } => {
            let mut doms: Vec<&TheoryObject<T>> = vec![dom];
            let mut cods: Vec<&TheoryObject<T>> = vec![cod];
            for a in rest {
                let TheoryArrow::Generator { name: n, dom: d, cod: c } = a else {
                    return UnificationResult::Incompatible;
                };
                if n != name {
                    return UnificationResult::Incompatible;
                }
                doms.push(d);
                cods.push(c);
            }
            let UnificationResult::MostSpecific(dom) = T::unify_objects(&doms) else {
                return UnificationResult::Incompatible;
            };
            let UnificationResult::MostSpecific(cod) = T::unify_objects(&cods) else {
                return UnificationResult::Incompatible;
            };
            UnificationResult::MostSpecific(TheoryArrow::Generator { name: name.clone(), dom, cod })
        }

        TheoryArrow::ModalApplication { on } => {
            let mut children: Vec<&TheoryArrow<T>> = vec![on.as_ref()];
            for a in rest {
                let TheoryArrow::ModalApplication { on } = a else {
                    return UnificationResult::Incompatible;
                };
                children.push(on.as_ref());
            }
            unify_arrow(&children).map(|child| TheoryArrow::ModalApplication {
                on: Box::new(child),
            })
        }
        TheoryArrow::ModalStructureMap { map } => {
            if rest.iter().all(|a| {
                matches!(a, TheoryArrow::ModalStructureMap { map: other } if other == map)
            }) {
                UnificationResult::MostSpecific(TheoryArrow::ModalStructureMap {
                    map: map.clone(),
                })
            } else {
                UnificationResult::Incompatible
            }
        }
    }
}

/// TODO: doc --- put a [Composite] of [TheoryArrow]s into the epi-mono normal
/// form for the theory's [ListModality] structure maps, using
/// [StructureMap::compose], [StructureMap::lift], and [StructureMap::unlift].
fn destruct_normalise_composite<T: Theory>(c: &Composite<TheoryArrow<T>>) -> Vec<TheoryArrow<T>> {
    let _ = c;
    todo!("destruct_normalise_composite using the epi-mono normal form of T::ListModality")
}
