[package]
name = "catlaborator"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
bumpalo = { version = "3.18.1", features = ["collections"] }
catlog = { version = "0.1.0", path = "../catlog" }
expect-test = "1.5.1"
fexplib = { path = "/home/o/g/ToposInstitute/fexplib" }
indoc = "2.0.6"
pretty = "0.12.4"
pretty-util = "0.1.0"
tattle = { path = "/home/o/g/ToposInstitute/tattle" }
ustr = "1"
uuid = { version = "=1.11", features = ["v7", "serde", "js"] }
serde = { version = "1", features = ["derive"] }
tsify = { version = "0.5", features = ["js"] }
wasm-bindgen = "0.2.100"
notebook-types = { version = "0.1.0", path = "../notebook-types" }
catlog-wasm = { version = "0.1.0", path = "../catlog-wasm" }
js-sys = "0.3.77"
web-sys = { version = "0.3.77", features = ["console"] }
bwd = "0.2.1"
egglog = "0.5.0"
