[build]
publish = "dist/"
command = "rustup toolchain install stable && rustup target add wasm32-unknown-unknown && npm run build"

[build.environment]
RUST_VERSION = "1.81.0"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
