// This file was generated by [rspc](https://github.com/oscartbeaumont/rspc). Do not edit this file manually.

export type Procedures = {
    queries: 
        { key: "doc_id", input: string, result: string },
    mutations: 
        { key: "new_ref", input: string, result: NewRef },
    subscriptions: never
};

export type NewRef = { refId: string; docId: string }
