// This file was generated by [rspc](https://github.com/oscartbeaumont/rspc). Do not edit this file manually.

export type Procedures = {
    queries: 
        { key: "doc_id", input: string, result: string },
    mutations: 
        { key: "new_ref", input: any, result: string } | 
        { key: "save_snapshot", input: RefContent, result: null },
    subscriptions: never
};

export type RefContent = { refId: string; content: any }
