CREATE TABLE snapshots (
    id INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    for_ref UUID NOT NULL,
    content JSONB NOT NULL,
    at_time TIMESTAMPTZ NOT NULL
);

CREATE TABLE refs (
    id UUID PRIMARY KEY,
    head INT NOT NULL REFERENCES snapshots (id)
);

ALTER TABLE snapshots
    ADD FOREIGN KEY (for_ref) REFERENCES refs (id) DEFERRABLE INITIALLY DEFERRED;
