# TODO make this automatically generated by CatColab
""" Common types useful for deserializing CatColab JSON payloads """
module Types 

export ObType, MorType, DiagramObGenerator, DiagramMorGenerator, ObGenerator, 
       MorGenerator, Diagram, Model, ModelDiagram

using StructTypes

struct ObType 
    tag::String 
    content::String
end
StructTypes.StructType(::Type{ObType}) = StructTypes.Struct()

struct MorType 
    tag::String 
    content::Union{String,ObType}
end
StructTypes.StructType(::Type{MorType}) = StructTypes.Struct()

struct DiagramObGenerator 
    id::String
    label::Vector{String}
    obType::ObType
    over::ObType
end 
StructTypes.StructType(::Type{DiagramObGenerator}) = StructTypes.Struct()

struct DiagramMorGenerator
    id::String
    morType::MorType
    over::ObType
    dom::ObType
    cod::ObType
end
StructTypes.StructType(::Type{DiagramMorGenerator}) = StructTypes.Struct()

struct ObGenerator 
    id::String
    label::Vector{String}
    obType::ObType
end 
StructTypes.StructType(::Type{ObGenerator}) = StructTypes.Struct()

struct MorGenerator
    id::String
    label::Vector{String}
    morType::MorType
    dom::ObType
    cod::ObType
end
StructTypes.StructType(::Type{MorGenerator}) = StructTypes.Struct()

struct Diagram 
    obGenerators::Vector{DiagramObGenerator}
    morGenerators::Vector{DiagramMorGenerator}
end
StructTypes.StructType(::Type{Diagram}) = StructTypes.Struct()

struct Model 
    obGenerators::Vector{ObGenerator}
    morGenerators::Vector{MorGenerator}
end
StructTypes.StructType(::Type{Model}) = StructTypes.Struct()


struct ModelDiagram 
    model::Model
    diagram::Diagram
end
StructTypes.StructType(::Type{ModelDiagram}) = StructTypes.Struct()

end # module
