//! Generate catlog models from DoubleTT types.

use all_the_same::all_the_same;
use derive_more::{From, TryInto};
use tattle::display::SourceInfo;

use super::{eval::*, prelude::*, text_elab, theory::*, toplevel::*, val::*};
use crate::dbl::{
    discrete, discrete_tabulator, modal,
    model::{DblModel, DblModelPrinter, MutDblModel},
    model_diagram::DblModelDiagram,
    theory::{DblTheory, DblTheoryKind, NonUnital, Unital},
};
use crate::one::{
    Category, QualifiedPath,
    path::{Path, PathEq},
};
use crate::zero::{Namespace, QualifiedName};

/// A model generated by DoubleTT.
///
/// Similarly to [`TheoryDef`], this enum boxes the different types of models
/// that can be generated by DoubleTT.
pub enum Model {
    /// A model of a discrete double theory.
    Discrete(Box<discrete::DiscreteDblModel>),
    /// A model of a discrete tabulator theory.
    DiscreteTab(Box<discrete_tabulator::DiscreteTabModel>),
    /// A model of a unital modal double theory.
    ModalUnital(Box<modal::ModalDblModel<Unital>>),
    /// A model of a non-unital modal double theory.
    ModalNonUnital(Box<modal::ModalDblModel<NonUnital>>),
}

/// An object in a model generated by DoubleTT.
#[derive(Debug, From, TryInto)]
enum Ob {
    Discrete(QualifiedName),
    DiscreteTab(discrete_tabulator::TabOb),
    Modal(modal::ModalOb),
}

/// A morphism in a model generated by DoubleTT.
#[derive(Debug, From, TryInto)]
enum Mor {
    Discrete(Path<QualifiedName, QualifiedName>),
    DiscreteTab(discrete_tabulator::TabMor),
    Modal(modal::ModalMor),
}

impl Model {
    /// Constructs an empty model of a theory.
    pub fn new(theory: &TheoryDef) -> Self {
        match theory {
            TheoryDef::Discrete(theory) => {
                Model::Discrete(Box::new(discrete::DiscreteDblModel::new(theory.clone())))
            }
            TheoryDef::DiscreteTab(theory) => Model::DiscreteTab(Box::new(
                discrete_tabulator::DiscreteTabModel::new(theory.clone()),
            )),
            TheoryDef::ModalUnital(theory) => {
                Model::ModalUnital(Box::new(modal::ModalDblModel::new(theory.clone())))
            }
            TheoryDef::ModalNonUnital(theory) => {
                Model::ModalNonUnital(Box::new(modal::ModalDblModel::new(theory.clone())))
            }
        }
    }

    /// Parses and generates a model from plain text.
    ///
    /// If there is an error in parsing, an error message is returned.
    pub fn from_text(th: &TheoryDef, s: &str) -> Result<Self, String> {
        let theory = Theory::new("_".into(), th.clone());
        let reporter = Reporter::new();
        let toplevel: Toplevel = Default::default();
        let maybe_elab = text_elab::TT_PARSE_CONFIG.with_parsed(s, reporter.clone(), |fntn| {
            let mut elaborator = text_elab::Elaborator::new(theory, reporter.clone(), &toplevel);
            Some(elaborator.ty(fntn))
        });
        if let Some((_, ty_v)) = maybe_elab
            && !reporter.errored()
        {
            let (model, _) = Self::from_ty(&toplevel, th, &ty_v);
            Ok(model)
        } else {
            let source_info = SourceInfo::new(None, s);
            Err(source_info.extract_report_to_string(reporter))
        }
    }

    /// Generates a model from a type.
    ///
    /// Precondition: `ty` must be valid in the empty context.
    pub fn from_ty(toplevel: &Toplevel, th: &TheoryDef, ty: &TyV) -> (Self, Namespace) {
        let mut generator = ModelGenerator::new(toplevel, th);
        let namespace = generator.generate(ty);
        (generator.model, namespace)
    }

    /// Tries to extract a model of a discrete theory.
    pub fn as_discrete(self) -> Option<discrete::DiscreteDblModel> {
        match self {
            Model::Discrete(model) => Some(*model),
            _ => None,
        }
    }

    /// Tries to extract a model of a unital modal theory.
    pub fn as_modal(self) -> Option<modal::ModalDblModel<Unital>> {
        match self {
            Model::ModalUnital(model) => Some(*model),
            _ => None,
        }
    }

    /// Tries to extract a model of a non-unital modal theory.
    pub fn as_modal_non_unital(self) -> Option<modal::ModalDblModel<NonUnital>> {
        match self {
            Model::ModalNonUnital(model) => Some(*model),
            _ => None,
        }
    }

    /// Constructs the identity morphism on an object.
    fn id(&self, ob: Ob) -> Mor {
        all_the_same!(match self {
            Model::[Discrete, ModalUnital, DiscreteTab, ModalNonUnital](model) => {
                model.id(ob.try_into().unwrap()).into()
            }
        })
    }

    /// Composes a pair of morphisms.
    fn compose2(&self, mor1: Mor, mor2: Mor) -> Mor {
        all_the_same!(match self {
            Model::[Discrete, DiscreteTab, ModalUnital, ModalNonUnital](model) => {
                model.compose2(mor1.try_into().unwrap(), mor2.try_into().unwrap()).into()
            }
        })
    }

    /// Tabulates a morphism, if possible.
    fn tabulated(&self, mor: Mor) -> Option<Ob> {
        match self {
            Model::Discrete(_) => None,
            Model::DiscreteTab(model) => Some(model.tabulated(mor.try_into().unwrap()).into()),
            Model::ModalUnital(_) | Model::ModalNonUnital(_) => None,
        }
    }

    /// Adds an object generator to the model.
    fn add_ob(&mut self, name: QualifiedName, ob_type: ObType) {
        all_the_same!(match self {
            Model::[Discrete, DiscreteTab, ModalUnital, ModalNonUnital](model) => {
                model.add_ob(name, ob_type.try_into().unwrap())
            }
        });
    }

    /// Adds a morphism generator to the model.
    fn add_mor(&mut self, name: QualifiedName, dom: Ob, cod: Ob, mor_type: MorType) {
        all_the_same!(match self {
            Model::[Discrete, DiscreteTab, ModalUnital, ModalNonUnital](model) => {
                model.add_mor(
                    name,
                    dom.try_into().unwrap(),
                    cod.try_into().unwrap(),
                    mor_type.try_into().unwrap()
                );
            }
        });
    }

    /// Adds an equation between two morphisms to the model.
    fn add_equation(&mut self, lhs: Mor, rhs: Mor) {
        match self {
            Model::Discrete(model) => {
                model.add_equation(PathEq::new(lhs.try_into().unwrap(), rhs.try_into().unwrap()));
            }
            Model::DiscreteTab(_) => {
                // Discrete tabulator models currently do not support equations, so we ignore them.
            }
            Model::ModalUnital(_) | Model::ModalNonUnital(_) => {
                // Modal models currently do not support equations, so we ignore them.
            }
        }
    }

    /// Pretty prints a summary of the model.
    pub fn summary(&self, printer: &DblModelPrinter) -> String {
        all_the_same!(match self {
            Model::[Discrete, DiscreteTab, ModalUnital, ModalNonUnital](model) => printer.summary(model.as_ref())
        })
    }

    /// Pretty prints the model in the given namespace.
    pub fn to_doc<'a>(&self, printer: &DblModelPrinter, ns: &Namespace) -> D<'a> {
        all_the_same!(match self {
            Model::[Discrete, DiscreteTab, ModalUnital, ModalNonUnital](model) => printer.namespaced_doc(model.as_ref(), ns, ns)
        })
    }
}

struct ModelGenerator<'a> {
    eval: Evaluator<'a>,
    theory: TheoryDef,
    model: Model,
}

impl<'a> ModelGenerator<'a> {
    fn new(toplevel: &'a Toplevel, theory: &TheoryDef) -> Self {
        let eval = Evaluator::empty(toplevel);
        let theory = theory.clone();
        let model = Model::new(&theory);
        Self { eval, theory, model }
    }

    fn generate(&mut self, ty: &TyV) -> Namespace {
        let tm_n;
        (tm_n, self.eval) = self.eval.bind_self(ty.clone());
        let tm_v = self.eval.eta_neu(&tm_n, ty);
        self.extract(vec![], &tm_v, ty).unwrap_or_else(Namespace::new_for_uuid)
    }

    /// Constructs a generating morphism.
    fn mor_generator(&self, name: QualifiedName) -> Mor {
        match &self.model {
            Model::Discrete(_) => Mor::Discrete(Path::single(name)),
            Model::DiscreteTab(_) => Mor::DiscreteTab(name.into()),
            Model::ModalUnital(_) | Model::ModalNonUnital(_) => {
                Mor::Modal(modal::ModalMor::Generator(name))
            }
        }
    }

    /// Constructs an application of an object operation, if the theory is modal.
    ///
    /// Returns the constructed object along with the expected object type of the result.
    fn ob_app(&self, name: &NameSegment, tm_v: &TmV) -> Option<(Ob, ObType)> {
        let name: QualifiedName = [*name].into();
        match &self.model {
            Model::Discrete(_) | Model::DiscreteTab(_) => None,
            Model::ModalUnital(model) => self.op_app_modal(model, name, tm_v),
            Model::ModalNonUnital(model) => self.op_app_modal(model, name, tm_v),
        }
    }

    fn op_app_modal<Kind: DblTheoryKind>(
        &self,
        model: &modal::ModalDblModel<Kind>,
        name: QualifiedName,
        tm_v: &TmV,
    ) -> Option<(Ob, ObType)> {
        let theory = model.theory();
        let op = modal::ModalObOp::generator(name.clone());
        let ot: ObType = theory.ob_op_cod(&op).into();
        let ob = self.make_ob_check_type(tm_v, &theory.ob_op_dom(&op).into())?;
        let ob = ob.try_into().unwrap();
        Some((Ob::Modal(modal::ModalOb::App(Box::new(ob), name)), ot))
    }

    /// Constructs a list of objects, if allowed.
    fn ob_list(&self, elems: Vec<Ob>, ob_type: &ObType) -> Option<Ob> {
        match &self.model {
            Model::Discrete(_) | Model::DiscreteTab(_) => None,
            Model::ModalUnital(_) | Model::ModalNonUnital(_) => {
                let ob_type: &modal::ModalObType = ob_type.try_into().unwrap();
                let Some(modal::Modality::List(list_type)) = ob_type.modalities.last() else {
                    unreachable!() // We know this is a list modality from the call site.
                };
                Some(Ob::Modal(modal::ModalOb::List(
                    *list_type,
                    elems.into_iter().map(|ob| ob.try_into().unwrap()).collect(),
                )))
            }
        }
    }

    /// Attempts to make an object of a model from a term.
    ///
    /// Returns the object together with the appropriate type.
    fn make_ob_synth_type(&self, val: &TmV) -> Option<(Ob, ObType)> {
        match &**val {
            TmV_::Neu(n, ty_v) => {
                let TyV_::Object(ob_type) = &**ty_v else {
                    return None;
                };
                let name = n.to_qualified_name();
                let ob = match &self.model {
                    Model::Discrete(_) => Ob::Discrete(name),
                    Model::DiscreteTab(_) => Ob::DiscreteTab(name.into()),
                    Model::ModalUnital(_) | Model::ModalNonUnital(_) => {
                        Ob::Modal(modal::ModalOb::Generator(name))
                    }
                };
                Some((ob, ob_type.clone()))
            }
            TmV_::App(name, tm_v) => self.ob_app(name, tm_v),
            TmV_::Tab(mor_tm_v) => {
                let (mor, mor_type) = self.synth_mor(mor_tm_v)?;
                Some((self.model.tabulated(mor)?, self.theory.tabulator(mor_type)?))
            }
            _ => None,
        }
    }

    /// Attempts to make an object of a model from a term.
    ///
    /// Also checks that the term constructs an object of the given type, returning only the object if successful.
    fn make_ob_check_type(&self, val: &TmV, ob_type: &ObType) -> Option<Ob> {
        match &**val {
            // ob_type checked recursively.
            TmV_::List(elems) => {
                let el_type = ob_type.clone().list_arg()?;
                let elems: Option<Vec<_>> =
                    elems.iter().map(|tm| self.make_ob_check_type(tm, &el_type)).collect();
                self.ob_list(elems?, ob_type)
            }
            _ => {
                let (ob, ot) = self.make_ob_synth_type(val)?;
                (ot == *ob_type).then_some(ob)
            }
        }
    }

    /// Attempts to make a morphism of a model from a term.
    ///
    /// Also returns the expected morphism type of the result.
    fn synth_mor(&self, val: &TmV) -> Option<(Mor, MorType)> {
        match &**val {
            TmV_::Neu(n, ty_v) => {
                let TyV_::Morphism(mor_type, _, _) = &**ty_v else {
                    return None;
                };
                let name = n.to_qualified_name();
                Some((self.mor_generator(name), mor_type.clone()))
            }
            TmV_::Id(x) => {
                let (dom, dom_type) = self.make_ob_synth_type(x)?;
                let mor_type = self.theory.hom_type(dom_type)?;
                Some((self.model.id(dom), mor_type))
            }
            TmV_::Compose(f, g) => {
                let (mf, mtf) = self.synth_mor(f)?;
                let (mg, mtg) = self.synth_mor(g)?;
                Some((self.model.compose2(mf, mg), self.theory.compose_types2(mtf, mtg)?))
            }
            _ => None,
        }
    }

    /// Attempts to make a morphism from a term of the given morphism type.
    ///
    /// At this time, all morphism constructors allow for type synthesis, but
    /// eventually this will change.
    fn make_mor(&self, val: &TmV, mor_type: &MorType) -> Option<Mor> {
        let (mor, mt) = self.synth_mor(val)?;
        (mt == *mor_type).then_some(mor)
    }

    fn extract(&mut self, prefix: Vec<NameSegment>, val: &TmV, ty: &TyV) -> Option<Namespace> {
        match &**ty {
            TyV_::Object(ot) => {
                self.model.add_ob(prefix.into(), ot.clone());
                None
            }
            TyV_::Morphism(mt, dom, cod) => {
                let dom = self.make_ob_check_type(dom, &self.theory.src_type(mt))?;
                let cod = self.make_ob_check_type(cod, &self.theory.tgt_type(mt))?;
                self.model.add_mor(prefix.into(), dom, cod, mt.clone());
                None
            }
            TyV_::Record(r) => {
                let mut namespace = Namespace::new_for_uuid();
                for (name, (label, _)) in r.fields.iter() {
                    let mut prefix = prefix.clone();
                    prefix.push(*name);
                    if let NameSegment::Uuid(uuid) = name {
                        namespace.set_label(*uuid, *label);
                    }
                    let field_tm_v = self.eval.proj(val, *name, *label);
                    let field_ty_v = self.eval.field_ty(ty, val, *name);
                    if let Some(inner) = self.extract(prefix, &field_tm_v, &field_ty_v) {
                        namespace.add_inner(*name, inner);
                    };
                }
                Some(namespace)
            }
            TyV_::Sing(_, _) => None,
            TyV_::Id(mor_ty, lhs, rhs) => {
                let TyV_::Morphism(mt, _, _) = &**mor_ty else {
                    return None;
                };
                if let (Some(lhs), Some(rhs)) = (self.make_mor(lhs, mt), self.make_mor(rhs, mt)) {
                    self.model.add_equation(lhs, rhs);
                }
                None
            }
            TyV_::Unit => None,
            TyV_::Meta(_) => None,
            TyV_::Over(_) => None,
        }
    }
}

/// Generates a [`DiscreteDblModelDiagram`] from an elaborated [`Diag`].
///
/// Restricted to discrete double theories for the moment; other theory
/// kinds will need their own diagram types in catlog before this can be
/// promoted to an enum mirroring [`Model`].
pub fn diagram_from_diag(
    toplevel: &Toplevel,
    th: &TheoryDef,
    diag: &Diag,
) -> Result<(discrete::DiscreteDblModelDiagram, Namespace), String> {
    let TheoryDef::Discrete(theory) = th else {
        return Err("diagram generation only supports discrete double theories".into());
    };
    let mut generator = DiagramGenerator {
        eval: Evaluator::empty(toplevel),
        codomain_ty: diag.model.clone(),
        domain: discrete::DiscreteDblModel::new(theory.clone()),
        mapping: discrete::DiscreteDblModelMapping::default(),
    };
    let namespace = generator.generate(&diag.body_val)?;
    let DiagramGenerator { domain, mapping, .. } = generator;
    Ok((DblModelDiagram(mapping, domain), namespace))
}

struct DiagramGenerator<'a> {
    eval: Evaluator<'a>,
    codomain_ty: TyV,
    domain: discrete::DiscreteDblModel,
    mapping: discrete::DiscreteDblModelMapping,
}

impl DiagramGenerator<'_> {
    fn generate(&mut self, body_ty: &TyV) -> Result<Namespace, String> {
        let (self_n, eval_with_self) = self.eval.bind_self(body_ty.clone());
        self.eval = eval_with_self;
        let self_val = self.eval.eta_neu(&self_n, body_ty);
        Ok(self
            .extract(vec![], &self_val, body_ty)?
            .unwrap_or_else(Namespace::new_for_uuid))
    }

    fn extract(
        &mut self,
        prefix: Vec<NameSegment>,
        val: &TmV,
        ty: &TyV,
    ) -> Result<Option<Namespace>, String> {
        match &**ty {
            TyV_::Record(r) => {
                let mut namespace = Namespace::new_for_uuid();
                for (name, (label, _)) in r.fields.iter() {
                    let mut child_prefix = prefix.clone();
                    child_prefix.push(*name);
                    if let NameSegment::Uuid(uuid) = name {
                        namespace.set_label(*uuid, *label);
                    }
                    let field_tm = self.eval.proj(val, *name, *label);
                    let field_ty = self.eval.field_ty(ty, val, *name);
                    if let Some(inner) = self.extract(child_prefix, &field_tm, &field_ty)? {
                        namespace.add_inner(*name, inner);
                    }
                }
                Ok(Some(namespace))
            }
            TyV_::Over(path) => {
                // Resolve the path against the codomain to find the
                // catlog object type for this generator.
                let (cod_self_n, cod_eval) = self.eval.bind_self(self.codomain_ty.clone());
                let cod_val = cod_eval.eta_neu(&cod_self_n, &self.codomain_ty);
                let resolved = cod_eval.path_ty(&self.codomain_ty, &cod_val, path)?;
                let TyV_::Object(ot) = &*resolved else {
                    return Err(
                        "@over path does not refer to an object generator in the codomain".into()
                    );
                };
                let ot: QualifiedName = ot.clone().try_into().map_err(|_| {
                    "@over codomain object type is not valid for a discrete theory".to_string()
                })?;
                let qname: QualifiedName = prefix.into();
                self.domain.add_ob(qname.clone(), ot);
                let target: QualifiedName =
                    path.iter().map(|(seg, _)| *seg).collect::<Vec<_>>().into();
                self.mapping.assign_ob(qname, target);
                Ok(None)
            }
            TyV_::Morphism(mt, dom, cod) => {
                // Augmentation produces lift morphisms whose dom and cod
                // are projections from the body's self, resolving to the
                // qualified names of generators (declared or specialized).
                let dom_name = neutral_qualified_name(dom).ok_or_else(|| {
                    "morphism domain does not resolve to a generator name".to_string()
                })?;
                let cod_name = neutral_qualified_name(cod).ok_or_else(|| {
                    "morphism codomain does not resolve to a generator name".to_string()
                })?;
                let mt_inner: QualifiedPath = mt
                    .clone()
                    .try_into()
                    .map_err(|_| "morphism type is not valid for a discrete theory".to_string())?;
                let qname: QualifiedName = prefix.clone().into();
                self.domain.add_mor(qname.clone(), dom_name, cod_name, mt_inner);
                // Mapping target: extract the codomain morphism's name
                // from the synthetic lift name `~f(e)`. For other shapes
                // (e.g., a future user-declared morphism in a body), fall
                // back to the field name itself.
                if let Some(last) = prefix.last()
                    && let Some(cod_mor) = parse_lift_morphism_name(last)
                {
                    let target = Path::single(QualifiedName::single(cod_mor));
                    self.mapping.assign_mor(qname, target);
                }
                Ok(None)
            }
            TyV_::Object(_) | TyV_::Sing(_, _) | TyV_::Id(_, _, _) | TyV_::Unit | TyV_::Meta(_) => {
                Ok(None)
            }
        }
    }
}

/// Read off a [`QualifiedName`] from a value that's a neutral chain of
/// projections from a self-variable (regardless of which level the self
/// is bound at). Returns `None` if the value isn't of that shape.
fn neutral_qualified_name(tm: &TmV) -> Option<QualifiedName> {
    let TmV_::Neu(n, _) = &**tm else {
        return None;
    };
    Some(n.to_qualified_name())
}

/// Parse a synthetic lift-morphism field name of the form `~f(e)` and
/// return the codomain morphism's name `f`. Returns `None` if the name
/// isn't of that shape.
fn parse_lift_morphism_name(name: &NameSegment) -> Option<NameSegment> {
    let NameSegment::Text(s) = name else {
        return None;
    };
    let s = s.as_str();
    let rest = s.strip_prefix('~')?;
    let paren = rest.find('(')?;
    Some(name_seg(ustr(&rest[..paren])))
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::dbl::model::FpDblModel;
    use crate::tt::text_elab::{TT_PARSE_CONFIG, TopElabResult, TopElaborator};
    use crate::tt::theory::std_theories;
    use crate::zero::Mapping;

    fn elaborate_to_toplevel(src: &str) -> Toplevel {
        let reporter = Reporter::new();
        let mut toplevel = Toplevel::new(std_theories());
        let _ = TT_PARSE_CONFIG.with_parsed_top(src, reporter.clone(), |topntns| {
            let mut topelab = TopElaborator::new(reporter.clone());
            for topntn in topntns.iter() {
                if let Some(TopElabResult::Declaration(name, decl)) =
                    topelab.elab(&toplevel, topntn)
                {
                    toplevel.declarations.insert(name, decl);
                }
            }
            Some(())
        });
        assert!(!reporter.errored(), "elaboration produced errors");
        toplevel
    }

    #[test]
    fn diagram_over_weighted_graph() {
        let src = r#"
set_theory ThSchema

type WeightedGraph := [
  V : Entity,
  E : Entity,
  Weight : AttrType,
  src : (Hom Entity)[E, V],
  tgt : (Hom Entity)[E, V],
  weight : Attr[E, Weight]
]

diagram I : @Instance(WeightedGraph) := [
    e : @over .E,
]
"#;
        let toplevel = elaborate_to_toplevel(src);
        let diag = match toplevel.declarations.get(&name_seg("I")) {
            Some(TopDecl::Diag(d)) => d.clone(),
            _ => panic!("expected I to be a diagram declaration"),
        };
        let (DblModelDiagram(mapping, domain), _ns) =
            diagram_from_diag(&toplevel, &diag.theory.definition, &diag).unwrap();

        let e_qname: QualifiedName = vec![name_seg("e")].into();
        let entity_ot: QualifiedName = vec![name_seg("Entity")].into();
        let e_target: QualifiedName = vec![name_seg("E")].into();

        assert!(domain.has_ob(&e_qname));
        assert_eq!(domain.ob_generator_type(&e_qname), entity_ot);
        assert_eq!(mapping.0.ob_generator_map.apply_to_ref(&e_qname), Some(e_target));
    }
}
