//! Generate catlog models from DoubleTT types.

use all_the_same::all_the_same;
use derive_more::{From, TryInto};
use tattle::display::SourceInfo;

use std::rc::Rc;

use super::{eval::*, prelude::*, text_elab, theory::*, toplevel::*, val::*};
use crate::dbl::{
    discrete::{self, DiscreteDblModelInstance, DiscreteInstanceTerm},
    discrete_tabulator, modal,
    model::{DblModel, DblModelPrinter, MutDblModel},
    theory::{DblTheory, DblTheoryKind, NonUnital, Unital},
};
use crate::one::{
    Category,
    path::{Path, PathEq},
};
use crate::zero::{Namespace, QualifiedName};

/// A model generated by DoubleTT.
///
/// Similarly to [`TheoryDef`], this enum boxes the different types of models
/// that can be generated by DoubleTT.
pub enum Model {
    /// A model of a discrete double theory.
    Discrete(Box<discrete::DiscreteDblModel>),
    /// A model of a discrete tabulator theory.
    DiscreteTab(Box<discrete_tabulator::DiscreteTabModel>),
    /// A model of a unital modal double theory.
    ModalUnital(Box<modal::ModalDblModel<Unital>>),
    /// A model of a non-unital modal double theory.
    ModalNonUnital(Box<modal::ModalDblModel<NonUnital>>),
}

/// An object in a model generated by DoubleTT.
#[derive(Debug, From, TryInto)]
enum Ob {
    Discrete(QualifiedName),
    DiscreteTab(discrete_tabulator::TabOb),
    Modal(modal::ModalOb),
}

/// A morphism in a model generated by DoubleTT.
#[derive(Debug, From, TryInto)]
enum Mor {
    Discrete(Path<QualifiedName, QualifiedName>),
    DiscreteTab(discrete_tabulator::TabMor),
    Modal(modal::ModalMor),
}

impl Model {
    /// Constructs an empty model of a theory.
    pub fn new(theory: &TheoryDef) -> Self {
        match theory {
            TheoryDef::Discrete(theory) => {
                Model::Discrete(Box::new(discrete::DiscreteDblModel::new(theory.clone())))
            }
            TheoryDef::DiscreteTab(theory) => Model::DiscreteTab(Box::new(
                discrete_tabulator::DiscreteTabModel::new(theory.clone()),
            )),
            TheoryDef::ModalUnital(theory) => {
                Model::ModalUnital(Box::new(modal::ModalDblModel::new(theory.clone())))
            }
            TheoryDef::ModalNonUnital(theory) => {
                Model::ModalNonUnital(Box::new(modal::ModalDblModel::new(theory.clone())))
            }
        }
    }

    /// Parses and generates a model from plain text.
    ///
    /// If there is an error in parsing, an error message is returned.
    pub fn from_text(th: &TheoryDef, s: &str) -> Result<Self, String> {
        let theory = Theory::new("_".into(), th.clone());
        let reporter = Reporter::new();
        let toplevel: Toplevel = Default::default();
        let maybe_elab = text_elab::TT_PARSE_CONFIG.with_parsed(s, reporter.clone(), |fntn| {
            let mut elaborator = text_elab::Elaborator::new(theory, reporter.clone(), &toplevel);
            Some(elaborator.ty(fntn))
        });
        if let Some((_, ty_v)) = maybe_elab
            && !reporter.errored()
        {
            let (model, _) = Self::from_ty(&toplevel, th, &ty_v);
            Ok(model)
        } else {
            let source_info = SourceInfo::new(None, s);
            Err(source_info.extract_report_to_string(reporter))
        }
    }

    /// Generates a model from a type.
    ///
    /// Precondition: `ty` must be valid in the empty context.
    pub fn from_ty(toplevel: &Toplevel, th: &TheoryDef, ty: &BaseTyV) -> (Self, Namespace) {
        let mut generator = ModelGenerator::new(toplevel, th);
        let namespace = generator.generate(ty);
        (generator.model, namespace)
    }

    /// Tries to extract a model of a discrete theory.
    pub fn as_discrete(self) -> Option<discrete::DiscreteDblModel> {
        match self {
            Model::Discrete(model) => Some(*model),
            _ => None,
        }
    }

    /// Tries to extract a model of a unital modal theory.
    pub fn as_modal(self) -> Option<modal::ModalDblModel<Unital>> {
        match self {
            Model::ModalUnital(model) => Some(*model),
            _ => None,
        }
    }

    /// Tries to extract a model of a non-unital modal theory.
    pub fn as_modal_non_unital(self) -> Option<modal::ModalDblModel<NonUnital>> {
        match self {
            Model::ModalNonUnital(model) => Some(*model),
            _ => None,
        }
    }

    /// Constructs the identity morphism on an object.
    fn id(&self, ob: Ob) -> Mor {
        all_the_same!(match self {
            Model::[Discrete, ModalUnital, DiscreteTab, ModalNonUnital](model) => {
                model.id(ob.try_into().unwrap()).into()
            }
        })
    }

    /// Composes a pair of morphisms.
    fn compose2(&self, mor1: Mor, mor2: Mor) -> Mor {
        all_the_same!(match self {
            Model::[Discrete, DiscreteTab, ModalUnital, ModalNonUnital](model) => {
                model.compose2(mor1.try_into().unwrap(), mor2.try_into().unwrap()).into()
            }
        })
    }

    /// Tabulates a morphism, if possible.
    fn tabulated(&self, mor: Mor) -> Option<Ob> {
        match self {
            Model::Discrete(_) => None,
            Model::DiscreteTab(model) => Some(model.tabulated(mor.try_into().unwrap()).into()),
            Model::ModalUnital(_) | Model::ModalNonUnital(_) => None,
        }
    }

    /// Adds an object generator to the model.
    fn add_ob(&mut self, name: QualifiedName, ob_type: ObType) {
        all_the_same!(match self {
            Model::[Discrete, DiscreteTab, ModalUnital, ModalNonUnital](model) => {
                model.add_ob(name, ob_type.try_into().unwrap())
            }
        });
    }

    /// Adds a morphism generator to the model.
    fn add_mor(&mut self, name: QualifiedName, dom: Ob, cod: Ob, mor_type: MorType) {
        all_the_same!(match self {
            Model::[Discrete, DiscreteTab, ModalUnital, ModalNonUnital](model) => {
                model.add_mor(
                    name,
                    dom.try_into().unwrap(),
                    cod.try_into().unwrap(),
                    mor_type.try_into().unwrap()
                );
            }
        });
    }

    /// Adds an equation between two morphisms to the model.
    fn add_equation(&mut self, lhs: Mor, rhs: Mor) {
        match self {
            Model::Discrete(model) => {
                model.add_equation(PathEq::new(lhs.try_into().unwrap(), rhs.try_into().unwrap()));
            }
            Model::DiscreteTab(_) => {
                // Discrete tabulator models currently do not support equations, so we ignore them.
            }
            Model::ModalUnital(_) | Model::ModalNonUnital(_) => {
                // Modal models currently do not support equations, so we ignore them.
            }
        }
    }

    /// Pretty prints a summary of the model.
    pub fn summary(&self, printer: &DblModelPrinter) -> String {
        all_the_same!(match self {
            Model::[Discrete, DiscreteTab, ModalUnital, ModalNonUnital](model) => printer.summary(model.as_ref())
        })
    }

    /// Pretty prints the model in the given namespace.
    pub fn to_doc<'a>(&self, printer: &DblModelPrinter, ns: &Namespace) -> D<'a> {
        all_the_same!(match self {
            Model::[Discrete, DiscreteTab, ModalUnital, ModalNonUnital](model) => printer.namespaced_doc(model.as_ref(), ns, ns)
        })
    }
}

struct ModelGenerator<'a> {
    eval: Evaluator<'a>,
    theory: TheoryDef,
    model: Model,
}

impl<'a> ModelGenerator<'a> {
    fn new(toplevel: &'a Toplevel, theory: &TheoryDef) -> Self {
        let eval = Evaluator::empty(toplevel);
        let theory = theory.clone();
        let model = Model::new(&theory);
        Self { eval, theory, model }
    }

    fn generate(&mut self, ty: &BaseTyV) -> Namespace {
        let tm_n;
        (tm_n, self.eval) = self.eval.bind_self(ty.clone());
        let tm_v = self.eval.eta_neu(&tm_n, ty);
        self.extract(vec![], &tm_v, ty).unwrap_or_else(Namespace::new_for_uuid)
    }

    /// Constructs a generating morphism.
    fn mor_generator(&self, name: QualifiedName) -> Mor {
        match &self.model {
            Model::Discrete(_) => Mor::Discrete(Path::single(name)),
            Model::DiscreteTab(_) => Mor::DiscreteTab(name.into()),
            Model::ModalUnital(_) | Model::ModalNonUnital(_) => {
                Mor::Modal(modal::ModalMor::Generator(name))
            }
        }
    }

    /// Constructs an application of an object operation, if the theory is modal.
    ///
    /// Returns the constructed object along with the expected object type of the result.
    fn ob_app(&self, name: &NameSegment, tm_v: &TmV) -> Option<(Ob, ObType)> {
        let name: QualifiedName = [*name].into();
        match &self.model {
            Model::Discrete(_) | Model::DiscreteTab(_) => None,
            Model::ModalUnital(model) => self.op_app_modal(model, name, tm_v),
            Model::ModalNonUnital(model) => self.op_app_modal(model, name, tm_v),
        }
    }

    fn op_app_modal<Kind: DblTheoryKind>(
        &self,
        model: &modal::ModalDblModel<Kind>,
        name: QualifiedName,
        tm_v: &TmV,
    ) -> Option<(Ob, ObType)> {
        let theory = model.theory();
        let op = modal::ModalObOp::generator(name.clone());
        let ot: ObType = theory.ob_op_cod(&op).into();
        let ob = self.make_ob_check_type(tm_v, &theory.ob_op_dom(&op).into())?;
        let ob = ob.try_into().unwrap();
        Some((Ob::Modal(modal::ModalOb::App(Box::new(ob), name)), ot))
    }

    /// Constructs a list of objects, if allowed.
    fn ob_list(&self, elems: Vec<Ob>, ob_type: &ObType) -> Option<Ob> {
        match &self.model {
            Model::Discrete(_) | Model::DiscreteTab(_) => None,
            Model::ModalUnital(_) | Model::ModalNonUnital(_) => {
                let ob_type: &modal::ModalObType = ob_type.try_into().unwrap();
                let Some(modal::Modality::List(list_type)) = ob_type.modalities.last() else {
                    unreachable!() // We know this is a list modality from the call site.
                };
                Some(Ob::Modal(modal::ModalOb::List(
                    *list_type,
                    elems.into_iter().map(|ob| ob.try_into().unwrap()).collect(),
                )))
            }
        }
    }

    /// Attempts to make an object of a model from a term.
    ///
    /// Returns the object together with the appropriate type.
    fn make_ob_synth_type(&self, val: &TmV) -> Option<(Ob, ObType)> {
        match &**val {
            TmV_::Neu(n, ty_v) => {
                let BaseTyV_::Object(ob_type) = &**ty_v else {
                    return None;
                };
                let name = n.to_qualified_name();
                let ob = match &self.model {
                    Model::Discrete(_) => Ob::Discrete(name),
                    Model::DiscreteTab(_) => Ob::DiscreteTab(name.into()),
                    Model::ModalUnital(_) | Model::ModalNonUnital(_) => {
                        Ob::Modal(modal::ModalOb::Generator(name))
                    }
                };
                Some((ob, ob_type.clone()))
            }
            TmV_::App(name, tm_v) => self.ob_app(name, tm_v),
            TmV_::Tab(mor_tm_v) => {
                let (mor, mor_type) = self.synth_mor(mor_tm_v)?;
                Some((self.model.tabulated(mor)?, self.theory.tabulator(mor_type)?))
            }
            _ => None,
        }
    }

    /// Attempts to make an object of a model from a term.
    ///
    /// Also checks that the term constructs an object of the given type, returning only the object if successful.
    fn make_ob_check_type(&self, val: &TmV, ob_type: &ObType) -> Option<Ob> {
        match &**val {
            // ob_type checked recursively.
            TmV_::List(elems) => {
                let el_type = ob_type.clone().list_arg()?;
                let elems: Option<Vec<_>> =
                    elems.iter().map(|tm| self.make_ob_check_type(tm, &el_type)).collect();
                self.ob_list(elems?, ob_type)
            }
            _ => {
                let (ob, ot) = self.make_ob_synth_type(val)?;
                (ot == *ob_type).then_some(ob)
            }
        }
    }

    /// Attempts to make a morphism of a model from a term.
    ///
    /// Also returns the expected morphism type of the result.
    fn synth_mor(&self, val: &TmV) -> Option<(Mor, MorType)> {
        match &**val {
            TmV_::Neu(n, ty_v) => {
                let BaseTyV_::Morphism(mor_type, _, _) = &**ty_v else {
                    return None;
                };
                let name = n.to_qualified_name();
                Some((self.mor_generator(name), mor_type.clone()))
            }
            TmV_::Id(x) => {
                let (dom, dom_type) = self.make_ob_synth_type(x)?;
                let mor_type = self.theory.hom_type(dom_type)?;
                Some((self.model.id(dom), mor_type))
            }
            TmV_::Compose(f, g) => {
                let (mf, mtf) = self.synth_mor(f)?;
                let (mg, mtg) = self.synth_mor(g)?;
                Some((self.model.compose2(mf, mg), self.theory.compose_types2(mtf, mtg)?))
            }
            _ => None,
        }
    }

    /// Attempts to make a morphism from a term of the given morphism type.
    ///
    /// At this time, all morphism constructors allow for type synthesis, but
    /// eventually this will change.
    fn make_mor(&self, val: &TmV, mor_type: &MorType) -> Option<Mor> {
        let (mor, mt) = self.synth_mor(val)?;
        (mt == *mor_type).then_some(mor)
    }

    fn extract(&mut self, prefix: Vec<NameSegment>, val: &TmV, ty: &BaseTyV) -> Option<Namespace> {
        match &**ty {
            BaseTyV_::Object(ot) => {
                self.model.add_ob(prefix.into(), ot.clone());
                None
            }
            BaseTyV_::Morphism(mt, dom, cod) => {
                let dom = self.make_ob_check_type(dom, &self.theory.src_type(mt))?;
                let cod = self.make_ob_check_type(cod, &self.theory.tgt_type(mt))?;
                self.model.add_mor(prefix.into(), dom, cod, mt.clone());
                None
            }
            BaseTyV_::Record(r) => {
                let mut namespace = Namespace::new_for_uuid();
                for (name, (label, _)) in r.fields.iter() {
                    let mut prefix = prefix.clone();
                    prefix.push(*name);
                    if let NameSegment::Uuid(uuid) = name {
                        namespace.set_label(*uuid, *label);
                    }
                    let field_tm_v = self.eval.proj(val, *name, *label);
                    let field_ty_v = self.eval.field_ty(ty, val, *name);
                    if let Some(inner) = self.extract(prefix, &field_tm_v, &field_ty_v) {
                        namespace.add_inner(*name, inner);
                    };
                }
                Some(namespace)
            }
            BaseTyV_::Sing(_, _) => None,
            BaseTyV_::Id(mor_ty, lhs, rhs) => {
                let BaseTyV_::Morphism(mt, _, _) = &**mor_ty else {
                    return None;
                };
                if let (Some(lhs), Some(rhs)) = (self.make_mor(lhs, mt), self.make_mor(rhs, mt)) {
                    self.model.add_equation(lhs, rhs);
                }
                None
            }
            BaseTyV_::Meta(_) => None,
            BaseTyV_::Over(_) => None,
        }
    }
}

/// Generates a [`DiscreteDblModelInstance`] from an elaborated [`Instance`]
/// declaration.
///
/// Walks the instance body's [`TmV_::Instance`] payload, registering
/// each generator with its fiber, each equation as a pair of
/// [`DiscreteInstanceTerm`]s, and each sub-instance's contents under
/// the appropriate prefix.
///
/// Restricted to discrete double theories for the moment.
pub fn instance_from_def(
    toplevel: &Toplevel,
    th: &TheoryDef,
    inst: &Instance,
) -> Result<(DiscreteDblModelInstance, Namespace), String> {
    let TheoryDef::Discrete(_) = th else {
        return Err("instance generation only supports discrete double theories".into());
    };
    let (cod_model, _) = Model::from_ty(toplevel, th, &inst.codomain);
    let cod_model = cod_model
        .as_discrete()
        .ok_or_else(|| "expected a discrete codomain model".to_string())?;
    let mut instance = DiscreteDblModelInstance::new(Rc::new(cod_model));
    let TmV_::Instance(body) = &*inst.val else {
        return Err("expected a TmV::Instance body".into());
    };
    let mut namespace = Namespace::new_for_uuid();
    extract_instance_body(&mut instance, &mut namespace, &[], body)?;
    Ok((instance, namespace))
}

fn extract_instance_body(
    instance: &mut DiscreteDblModelInstance,
    namespace: &mut Namespace,
    prefix: &[NameSegment],
    body: &InstanceBodyV,
) -> Result<(), String> {
    for (name, (label, path)) in &body.generators {
        if let NameSegment::Uuid(uuid) = name {
            namespace.set_label(*uuid, *label);
        }
        let mut qsegs = prefix.to_vec();
        qsegs.push(*name);
        let qname: QualifiedName = qsegs.into();
        let fiber: QualifiedName = path.iter().map(|(seg, _)| *seg).collect::<Vec<_>>().into();
        instance.add_generator(qname, fiber);
    }
    for (lhs, rhs) in &body.equations {
        let lhs_t = tm_to_discrete_instance_term_with_prefix(instance, lhs, prefix)?;
        let rhs_t = tm_to_discrete_instance_term_with_prefix(instance, rhs, prefix)?;
        instance.add_equation(lhs_t, rhs_t);
    }
    for (name, (label, sub_v)) in &body.sub_instances {
        if let NameSegment::Uuid(uuid) = name {
            namespace.set_label(*uuid, *label);
        }
        let TmV_::Instance(sub_body) = &**sub_v else {
            return Err("sub-instance is not a TmV::Instance".into());
        };
        let mut sub_prefix = prefix.to_vec();
        sub_prefix.push(*name);
        extract_instance_body(instance, namespace, &sub_prefix, sub_body)?;
    }
    Ok(())
}

/// Convert an `Over`-typed term value into a [`DiscreteInstanceTerm`],
/// prefixing each generator name with the path into any enclosing
/// sub-instances.
///
/// Nested [`TmV_::OverApp`]s are flattened into a single morphism path
/// applied to the generator at the leaf, matching the flat canonical
/// shape of [`DiscreteInstanceTerm`].
fn tm_to_discrete_instance_term_with_prefix(
    instance: &DiscreteDblModelInstance,
    tm: &TmV,
    prefix: &[NameSegment],
) -> Result<DiscreteInstanceTerm, String> {
    // Walk outer-to-inner, recording each applied morphism.
    let mut mors_outer_first: Vec<QualifiedName> = Vec::new();
    let mut cur = tm;
    let base: QualifiedName = loop {
        match &**cur {
            TmV_::Neu(n, _) => {
                let mut segs = prefix.to_vec();
                segs.extend(neu_full_name(n));
                break segs.into();
            }
            TmV_::OverApp(mor_name, _, _, inner) => {
                mors_outer_first.push(QualifiedName::single(*mor_name));
                cur = inner;
            }
            _ => return Err("term is not a generator or codomain-morphism application".into()),
        }
    };
    // Path order is innermost-first (apply first goes first).
    mors_outer_first.reverse();
    let path = match Path::from_vec(mors_outer_first) {
        Some(p) => p,
        None => {
            let fiber = instance
                .fiber_of(&base)
                .ok_or_else(|| format!("instance term mentions unknown generator {base}"))?;
            Path::Id(fiber.clone())
        }
    };
    Ok(DiscreteInstanceTerm { path, base })
}

/// Read off the full name of a neutral, including its leading variable
/// name and any subsequent projection segments. Unlike
/// [`TmN::to_qualified_name`] this does *not* treat the leading
/// variable as an implicit root — for instance-body terms the leading
/// variable is itself a generator name (e.g. `v1`) or sub-instance
/// name (e.g. `we`), and must contribute a segment.
fn neu_full_name(n: &TmN) -> Vec<NameSegment> {
    let mut segments = Vec::new();
    let mut cur = n;
    loop {
        match &**cur {
            TmN_::Var(_, name, _) => {
                segments.push(*name);
                break;
            }
            TmN_::Proj(n1, f, _) => {
                segments.push(*f);
                cur = n1;
            }
        }
    }
    segments.reverse();
    segments
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::tt::text_elab::{TT_PARSE_CONFIG, TopElabResult, TopElaborator};
    use crate::tt::theory::std_theories;

    fn elaborate_to_toplevel(src: &str) -> Toplevel {
        let reporter = Reporter::new();
        let mut toplevel = Toplevel::new(std_theories());
        let _ = TT_PARSE_CONFIG.with_parsed_top(src, reporter.clone(), |topntns| {
            let mut topelab = TopElaborator::new(reporter.clone());
            for topntn in topntns.iter() {
                if let Some(TopElabResult::Declaration(name, decl)) =
                    topelab.elab(&toplevel, topntn)
                {
                    toplevel.declarations.insert(name, decl);
                }
            }
            Some(())
        });
        assert!(!reporter.errored(), "elaboration produced errors");
        toplevel
    }

    #[test]
    fn instance_over_weighted_graph() {
        let src = r#"
set_theory ThSchema

model WeightedGraph := [
  V : Entity,
  E : Entity,
  Weight : AttrType,
  src : (Hom Entity)[E, V],
  tgt : (Hom Entity)[E, V],
  weight : Attr[E, Weight]
]

instance I : WeightedGraph := [
    V := [v],
    E := [e],
    src(e) := v
]
"#;
        let toplevel = elaborate_to_toplevel(src);
        let def = match toplevel.declarations.get(&name_seg("I")) {
            Some(TopDecl::Instance(i)) => i.clone(),
            _ => panic!("expected I to be an instance declaration"),
        };
        let (instance, _ns) = instance_from_def(&toplevel, &def.theory.definition, &def).unwrap();

        let e_qname: QualifiedName = vec![name_seg("e")].into();
        let e_fiber: QualifiedName = vec![name_seg("E")].into();
        assert_eq!(instance.fiber_of(&e_qname), Some(&e_fiber));
        assert_eq!(instance.equations().count(), 1);
    }

    /// An instance carrying fiber equations, imported as a sub-instance.
    ///
    /// Exercises the presented-representable synthesis: `Loop`'s type (as
    /// used by the import `l : Loop`) must carry an `Id`-typed field per
    /// fiber equation, and that type must quote/evaluate without panicking.
    /// Extraction of the importer must still recover both copies of the
    /// loop's structure.
    #[test]
    fn import_of_instance_with_fiber_equations() {
        let src = r#"
set_theory ThSchema

model WeightedGraph := [
  V : Entity,
  E : Entity,
  Weight : AttrType,
  src : (Hom Entity)[E, V],
  tgt : (Hom Entity)[E, V],
  weight : Attr[E, Weight]
]

instance Loop : WeightedGraph := [
    V := [v],
    E := [e],
    src(e) := v,
    tgt(e) := v
]

instance UseLoop : WeightedGraph := [
    l : Loop
]
"#;
        let toplevel = elaborate_to_toplevel(src);

        // `Loop`'s representable type must expose its two fiber equations as
        // `Id`-typed fields alongside the `e`/`v` generators, and quoting it
        // (which re-evaluates every field type against a bound `self`) must
        // not panic.
        let loop_def = match toplevel.declarations.get(&name_seg("Loop")) {
            Some(TopDecl::Instance(i)) => i.clone(),
            _ => panic!("expected Loop to be an instance declaration"),
        };
        let TmV_::Instance(loop_body) = &*loop_def.val else {
            panic!("Loop should evaluate to an instance");
        };
        let eval = Evaluator::empty(&toplevel);
        let body_ty = eval.synth_instance_body_ty(loop_body);
        let BaseTyV_::Record(r) = &*body_ty else {
            panic!("synthesized instance type should be a record");
        };
        assert!(r.fields.get(name_seg("e")).is_some(), "generator field e");
        assert!(r.fields.get(name_seg("v")).is_some(), "generator field v");
        assert!(r.fields.get(name_seg("_eq0")).is_some(), "first fiber equation");
        assert!(r.fields.get(name_seg("_eq1")).is_some(), "second fiber equation");
        // Round-trips through eval+quote of the dependent `Id` fields.
        let _ = eval.quote_ty(&body_ty);

        // The importer still extracts both generators and the imported
        // copy's two equations.
        let use_def = match toplevel.declarations.get(&name_seg("UseLoop")) {
            Some(TopDecl::Instance(i)) => i.clone(),
            _ => panic!("expected UseLoop to be an instance declaration"),
        };
        let (instance, _ns) =
            instance_from_def(&toplevel, &use_def.theory.definition, &use_def).unwrap();
        let le_qname: QualifiedName = vec![name_seg("l"), name_seg("e")].into();
        let e_fiber: QualifiedName = vec![name_seg("E")].into();
        assert_eq!(instance.fiber_of(&le_qname), Some(&e_fiber));
        assert_eq!(instance.equations().count(), 2);
    }
}
