// This file has been generated by Specta. DO NOT EDIT.

export type Path<V, E> = { start: V; path: E[] }

export type ColGraph<V, E> = { vertices: V[]; edges: E[]; src: { [key: E]: V }; tgt: { [key: E]: V } }

