// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The type/kind of a document, without any associated content.
 */
export type DocumentType = "model" | "diagram" | "analysis";
