// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PermissionLevel } from "./PermissionLevel";

/**
 * A new set of permissions to assign to a document.
 */
export type NewPermissions = { 
/**
 * Base permission level for any person, logged in or not.
 */
anyone: PermissionLevel | null, 
/** Permission levels for users.

    A mapping from user IDs to permission levels.
    */
users: { [key in string]?: PermissionLevel }, };
