// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue";
import type { Permissions } from "./Permissions";

/**
 * Input to the [`new_ref`] procedure.
 */
export type NewRef = { content: JsonValue, permissions?: Permissions, };
