// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PermissionLevel } from "./PermissionLevel";

/**
 * A permission entry to set on a document.
 */
export type PermissionToSet = { userId: string | null, level: PermissionLevel, };
