// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PermissionLevel } from "./PermissionLevel";

/**
 * Permissions set on a document.
 */
export type Permissions = { 
/**
 * Base permission level for any person, logged in or not.
 */
anyone?: PermissionLevel, 
/**
 * Permission level for the current user.
 */
user?: PermissionLevel, 
/** Permission levels for all other users.

    Only owners of the document have access to this information.
     */
users?: { [key in string]?: PermissionLevel }, };
