// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Levels of permission that a user can have on a document.
 */
export type PermissionLevel = "Read" | "Write" | "Maintain" | "Own";
