// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PermissionLevel } from "./PermissionLevel";

/**
 * Global and user permission levels on a document.
 */
export type Permissions = { anyone: PermissionLevel | null, user: PermissionLevel | null, };
