// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PermissionLevel } from "./PermissionLevel";

/**
 * Permissions set on a document.
 */
export type Permissions = { 
/**
 * Permission level of anyone, logged in or not.
 */
anyone?: PermissionLevel, 
/**
 * Permission level of the current user, if any.
 */
user?: PermissionLevel, 
/**
 * Permission levels of all other users.
 */
users: { [key in string]?: PermissionLevel }, };
