// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PermissionLevel } from "./PermissionLevel";

/**
 * Parameters for filtering a search of refs
 */
export type RefQueryParams = { owner_username_query: string | null, ref_name_query: string | null, searcher_min_level: PermissionLevel | null, include_public_documents: boolean | null, };
