// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Parameters for filtering a search of refs
 */
export type RefQueryParams = { owner_username_query: string | null, ref_name_query: string | null, };
