// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A subset of user relevant information about a ref. Used for showing
 * users information on a variety of refs without having to load whole
 * refs.
 */
export type RefStub = { name: string, ref_id: string, };
