// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Data of a user profile.
 */
export type UserProfile = { username: string | null, display_name: string | null, };
