// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PermissionLevel } from "./PermissionLevel";
import type { UserSummary } from "./UserSummary";

/**
 * Permissions of a user on a document.
 */
export type UserPermissions = { user: UserSummary, level: PermissionLevel, };
