// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Summary of a user.
 *
 * The minimal information needed to uniquely identify a user and display the user
 * in human-readable form.
 */
export type UserSummary = { id: string, username: string | null, displayName: string | null, };
