// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PermissionLevel } from "./PermissionLevel";

/**
 * Document reference information for user state synchronization.
 *
 * Contains lightweight metadata about a document that the user has access to.
 */
export type DocInfo = { 
/**
 * The name of the document.
 */
name: string, 
/**
 * The type of the document (e.g., "notebook", "theory").
 */
typeName: string, 
/**
 * The theory of the document, if it is a model.
 */
theory: string | null, 
/**
 * All permissions on this document (users and public).
 */
permissions: Array<PermissionInfo>, 
/**
 * When this document was created.
 */
createdAt: number, 
/**
 * When this document was deleted, if applicable.
 */
deletedAt: number | null, 
/**
 * The parent document ref ID, if this document has a parent.
 */
parent: Uint8Array | null, 
/**
 * The ref IDs of child documents.
 */
children: Array<Uint8Array>, };

/**
 * A single permission entry for a document in user state.
 *
 * Represents one user's (or the public "anyone") permission level on a document.
 */
export type PermissionInfo = { 
/**
 * The user ID this permission applies to, or `None` for the public "anyone" permission.
 */
user: string | null, 
/**
 * The permission level granted.
 */
level: PermissionLevel, };

/**
 * User info for user state synchronization.
 *
 * This is similar to [`crate::user::UserSummary`] but uses [`Text`] instead of [`String`]
 * for compatibility with Automerge/Autosurgeon serialization.
 */
export type UserInfo = { 
/**
 * The user's chosen username, if set.
 */
username: string | null, 
/**
 * The user's display name, if set.
 */
displayName: string | null, };

/**
 * State associated with a user, synchronized via Automerge.
 */
export type UserState = { 
/**
 * The user's own profile information.
 */
profile: UserInfo, 
/**
 * All users referenced in document permissions, keyed by user ID.
 */
knownUsers: { [key in string]?: UserInfo }, 
/**
 * The document refs accessible to the user, keyed by ref UUID string.
 * We cannot use the Uuid type here because Automerge requires the keys to have a `AsRef<str>` impl.
 */
documents: { [key in string]?: DocInfo }, };
