name: ci

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  nix_checks:
    name: nix checks
    runs-on: ubuntu-latest
    strategy:
      matrix:
        check: [rustFmt, rustClippy, rustTests, rustDocsCheck, generatedBindingsCheck, npmChecks]
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v25
      - uses: cachix/cachix-action@v14
        with:
          name: catcolab-jmoggr
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - name: Run ${{ matrix.check }}
        run: nix build .#checks.x86_64-linux.${{ matrix.check }}
      - name: Show build logs on failure
        if: failure()
        run: |
          nix log .#checks.x86_64-linux.${{ matrix.check }}
          exit 1

  ui_components_tests:
    name: ui-components tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Install Playwright browser
        run: pnpm --filter ./packages/ui-components exec playwright install chromium

      - name: Run ui-components tests
        run: pnpm --filter ./packages/ui-components run test

  build_nixos_system:
    name: build NixOS system
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config: [catcolab-next, catcolab]
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v25
      - uses: cachix/cachix-action@v14
        with:
          name: catcolab-jmoggr
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - run: nix build .#nixosConfigurations.${{ matrix.config }}.config.system.build.toplevel

  frontend_tests_with_backend:
    name: frontend tests with backend
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install Nix
      uses: cachix/install-nix-action@v25

    - name: Configure Cachix
      uses: cachix/cachix-action@v14
      with:
        name: catcolab-jmoggr
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

    - name: Run frontend tests with VM
      run: |
        nix build .#checks.x86_64-linux.frontendTests -L --no-sandbox
