name: GitHub PR Sync with Notion

on:
  pull_request:
    types: [opened, edited, closed]

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      issues: write
    steps:
      - name: Sync to Notion
        uses: isoppp/github-pr-sync-with-notion@v0.2.0
        with:
          notion_token: ${{ secrets.NOTION_TOKEN }}
          notion_database_id: ${{ secrets.NOTION_DATABASE_ID }}
          notion_id_property: 'ID'
          notion_status_property: 'Status'
          notion_status_value_done: 'Done'
          notion_pr_property: 'GitHub PR'
          pr_title_prefix: 'OBEE'
