name: ui-components-tests

on:
  push:
    branches:
      - main
    paths:
      - "packages/ui-components/**"
      - "package.json"
      - "pnpm-lock.yaml"
      - "pnpm-workspace.yaml"
      - ".github/workflows/ui-components-tests.yml"
  pull_request:
    paths:
      - "packages/ui-components/**"
      - "package.json"
      - "pnpm-lock.yaml"
      - "pnpm-workspace.yaml"
      - ".github/workflows/ui-components-tests.yml"

jobs:
  ui-components-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: "pnpm"

      - name: Install dependencies
        env:
          PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: "1"
        run: pnpm install

      - name: Install Playwright browser
        run: pnpm --filter ./packages/ui-components exec playwright install --with-deps chromium-headless-shell

      - name: Run ui-components tests
        run: pnpm --filter ./packages/ui-components run test
