name: vite-plugin-monorepo-dedupe

on:
  push:
    branches:
      - main
    paths:
      - "tools/vite-plugin-monorepo-dedupe/**"
      - "package.json"
      - "pnpm-lock.yaml"
      - "pnpm-workspace.yaml"
      - ".github/workflows/vite-plugin-monorepo-dedupe-checks.yml"
  pull_request:
    paths:
      - "tools/vite-plugin-monorepo-dedupe/**"
      - "package.json"
      - "pnpm-lock.yaml"
      - "pnpm-workspace.yaml"
      - ".github/workflows/vite-plugin-monorepo-dedupe-checks.yml"

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Run vite-plugin-monorepo-dedupe checks
        run: pnpm --filter ./tools/vite-plugin-monorepo-dedupe run ci
